-- 08 票：Agent 可观测性（agent-decision-layer）。
--
-- agent_runs：一次 Agent 运行的不可变关联锚点。run_id 由 Agent 编排层生成
-- （"run_"+32 位 hex，与审计 trace_id/request_id 同值，双向可追溯）。
-- 生命周期两段写入：runStarted 先落 RUNNING 行（started_at，finished_at 为空，
-- 进程中断时留 RUNNING 行即可检出中断）；runFinished 收口为 SUCCESS/FAILED
-- （error_type 只取 AgentFailureCode 稳定枚举或编排层内部收口码）。
-- input 只存 SHA-256 digest 不存原文；business_entity_type/id 供业务实体双向追溯
-- （如 PROCUREMENT_TICKET / id）。
CREATE TABLE app.agent_runs (
    run_id                  VARCHAR(36) PRIMARY KEY
                            CHECK (run_id ~ '^run_[0-9a-f]{32}$'),
    thread_id               VARCHAR(128) NOT NULL DEFAULT '',
    agent_slug              VARCHAR(64) NOT NULL
                            CHECK (agent_slug ~ '^[a-z][a-z0-9-]{0,63}$'),
    agent_version           VARCHAR(64),
    prompt_version          VARCHAR(64),
    model                   VARCHAR(128) NOT NULL,
    input_digest            CHAR(64) NOT NULL CHECK (input_digest ~ '^[0-9a-f]{64}$'),
    status                  VARCHAR(16) NOT NULL DEFAULT 'RUNNING'
                            CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    error_type              VARCHAR(64),
    latency_ms              INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
    token_usage             JSONB CHECK (token_usage IS NULL OR jsonb_typeof(token_usage) = 'object'),
    business_entity_type    VARCHAR(64),
    business_entity_id      VARCHAR(128),
    started_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (btrim(agent_slug) <> ''),
    CHECK (btrim(model) <> ''),
    CHECK ((status = 'RUNNING') = (finished_at IS NULL)),
    CHECK ((status = 'FAILED') = (error_type IS NOT NULL))
);

-- agent_tool_calls：一次 Agent 运行内的工具调用序列（run_id + 序号唯一）。
-- 参数/结果只存经 SecretRedactor 脱敏后的摘要（截断），不落敏感原文。
-- run_id 不设外键：05/06 业务 Agent（采购比价/数据查询）与门面共用同一工具桥接，
-- 其编排层尚未落 agent_run 行（后续票承接），外键会把它们的工具观测整体丢弃；
-- 以索引 + 应用层 run_id 关联（孤儿行仍可按 run_id 重放与关联审计）。
CREATE TABLE app.agent_tool_calls (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              VARCHAR(36) NOT NULL,
    sequence_no         INTEGER NOT NULL CHECK (sequence_no > 0),
    tool_name           VARCHAR(128) NOT NULL,
    args_summary        TEXT,
    result_summary      TEXT,
    latency_ms          INTEGER CHECK (latency_ms IS NULL OR latency_ms >= 0),
    status              VARCHAR(16) NOT NULL CHECK (status IN ('SUCCESS', 'FAILED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, sequence_no),
    CHECK (btrim(tool_name) <> '')
);

CREATE INDEX idx_agent_runs_slug_started ON app.agent_runs(agent_slug, started_at DESC);
CREATE INDEX idx_agent_runs_business_entity
    ON app.agent_runs(business_entity_type, business_entity_id)
    WHERE business_entity_type IS NOT NULL;
CREATE INDEX idx_agent_tool_calls_run ON app.agent_tool_calls(run_id, sequence_no);
