CREATE TABLE IF NOT EXISTS app.channel_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel             VARCHAR(32) NOT NULL DEFAULT 'WECOM' CHECK (channel = 'WECOM'),
    corp_id             VARCHAR(128) NOT NULL,
    connection_id       VARCHAR(128) NOT NULL,
    bot_id              VARCHAR(128) NOT NULL,
    message_id          VARCHAR(255) NOT NULL,
    chat_id             VARCHAR(255) NOT NULL,
    chat_type           VARCHAR(32) NOT NULL CHECK (chat_type IN ('group', 'single')),
    sender_user_id      VARCHAR(255) NOT NULL,
    message_type        VARCHAR(32) NOT NULL,
    content             TEXT NOT NULL,
    quote_type          VARCHAR(32),
    quote_content       TEXT,
    raw_payload         JSONB NOT NULL CHECK (jsonb_typeof(raw_payload) = 'object'),
    received_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (corp_id, connection_id, message_id),
    CHECK (btrim(corp_id) <> ''),
    CHECK (btrim(connection_id) <> ''),
    CHECK (btrim(bot_id) <> ''),
    CHECK (btrim(message_id) <> ''),
    CHECK (btrim(chat_id) <> ''),
    CHECK (btrim(sender_user_id) <> ''),
    CHECK (btrim(message_type) <> '')
);

CREATE INDEX IF NOT EXISTS idx_channel_messages_received
    ON app.channel_messages (received_at DESC, id DESC);
