-- ---------------------------------------------------------------------------
-- 京东云仓履约闭环：Shipment 级京东出库集成记录
-- ---------------------------------------------------------------------------
-- 本迁移在发布前被纠正：旧版本向 app.fulfillments 追加 jd_erp_delivery_no / jd_sync_status
-- （按逐行 Fulfillment 承载京东出库单号与同步状态），违反「一个 Shipment 最多一张京东出库单」
-- 的批次边界，也会把 JD 集成状态与 OrderLine 权威 processing_stage 混在一起。
-- 旧文件从未提交/发布（仅存在于本地工作区），因此直接原地纠正，不做 expand-migrate-contract。
--
-- 新边界（jd-fulfillment-loop/01）：
--   * app.shipment_jd_outbounds 与 app.shipments 一对一，同批次全部 ShipmentItem/Fulfillment 共享；
--   * erp_delivery_no = shipments.outbound_order_no（系统生成的稳定商户侧出库引用，提交给京东作 erpDeliveryNo）；
--   * sync_status / failure_phase / retry_count / last_error_* / request_hash 均为 JD 集成状态，
--     与 OrderLine processing_stage（权威业务阶段）完全分离。
-- ---------------------------------------------------------------------------

CREATE TABLE app.shipment_jd_outbounds (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         BIGINT NOT NULL UNIQUE REFERENCES app.shipments(id) ON DELETE RESTRICT,
    erp_delivery_no     VARCHAR(64) NOT NULL UNIQUE,
    jd_delivery_no      VARCHAR(64),
    sync_status         VARCHAR(32) NOT NULL DEFAULT 'NONE'
                        CHECK (sync_status IN ('NONE', 'SUBMITTING', 'SUBMITTED', 'SYNC_FAILED')),
    failure_phase       VARCHAR(32)
                        CHECK (failure_phase IS NULL OR failure_phase IN ('VALIDATION', 'SUBMIT')),
    retry_count         INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
    last_error_code     VARCHAR(64),
    last_error_message  TEXT,
    request_hash        CHAR(64),
    submitted_at        TIMESTAMPTZ,
    last_query_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (btrim(erp_delivery_no) <> ''),
    CHECK (request_hash IS NULL OR request_hash ~ '^[0-9a-f]{64}$'),
    CHECK ((last_error_code IS NULL) = (last_error_message IS NULL)),
    CHECK (sync_status <> 'SUBMITTED' OR submitted_at IS NOT NULL),
    CHECK (sync_status <> 'SYNC_FAILED' OR (failure_phase IS NOT NULL AND last_error_code IS NOT NULL)),
    CHECK (sync_status <> 'SUBMITTING' OR (request_hash IS NOT NULL AND retry_count > 0))
);

CREATE INDEX idx_shipment_jd_outbounds_sync
    ON app.shipment_jd_outbounds (sync_status)
    WHERE sync_status <> 'NONE';
