CREATE TABLE IF NOT EXISTS app.wecom_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     VARCHAR(64) NOT NULL CHECK (btrim(event_type) <> ''),
    msgid          VARCHAR(128) NOT NULL CHECK (btrim(msgid) <> ''),
    aibot_id       VARCHAR(128),
    chat_id        VARCHAR(255),
    chat_type      VARCHAR(32),
    from_user_id   VARCHAR(255),
    create_time    BIGINT,
    raw_payload    JSONB NOT NULL,
    received_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wecom_events_type_msgid
    ON app.wecom_events (event_type, msgid);
