-- Agent 平台化（meta-agent-platform-impl 票 01）：三表落地与播种。
--
-- 设计源：.scratch/meta-agent-platform/issues/03（版本状态机 + Schema 增量）、
-- 04（agent_runs 补 intent/provider，output_schema 修正）、05（guard_exemptions）、
-- 07（agent_eval_cases）、08（删除 permission_profile_ref，保留 tool_whitelist，新增 allow_write）。
--
-- 版本号说明：实施票标题写 V30，但 V30–V32 已被既有迁移占用，实际落地为 V33。
--
-- 播种纪律（03 决策 5 两步走）：本迁移只落结构与种子，三个业务 Agent 的代码定义
-- bean 并行保留（expand 阶段），注册表数据源切 DB 与代码定义删除由 T02 单独 commit。

-- ① agent_definitions：单表 append-only 全快照 + 三态版本状态机。
--    现有 AgentDefinition 8 字段 + id/version/status/activated_by/activated_at/
--    allow_write/guard_exemptions/output_schema（tool_whitelist = 现有 toolNames）。
--    「每 slug 至多一个 active」由部分唯一索引下沉到 DB；
--    enabled（运维启停）与 status（版本生命周期）正交。
CREATE TABLE app.agent_definitions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_slug          VARCHAR(64) NOT NULL
                        CHECK (agent_slug ~ '^[a-z][a-z0-9-]{0,63}$'),
    name                VARCHAR(128) NOT NULL CHECK (btrim(name) <> ''),
    description         VARCHAR(512) NOT NULL CHECK (btrim(description) <> ''),
    system_prompt       TEXT NOT NULL CHECK (btrim(system_prompt) <> ''),
    prompt_version      VARCHAR(64) NOT NULL CHECK (btrim(prompt_version) <> ''),
    model_ref           VARCHAR(128) NOT NULL CHECK (btrim(model_ref) <> ''),
    enabled             BOOLEAN NOT NULL DEFAULT true,
    version             INTEGER NOT NULL CHECK (version > 0),
    status              VARCHAR(16) NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft', 'active', 'retired')),
    activated_by        VARCHAR(128),
    activated_at        TIMESTAMPTZ,
    -- 写工具白名单元数据（08）：一期白名单即 profile；allow_write=true 才允许白名单含写工具。
    allow_write         BOOLEAN NOT NULL DEFAULT false,
    -- 平台默认守卫豁免（05）：枚举数组，默认空 = PII 守卫生效。
    guard_exemptions    JSONB NOT NULL DEFAULT '[]'::jsonb
                        CHECK (jsonb_typeof(guard_exemptions) = 'array'),
    -- 定义携带的输出 JSON schema（04 修正）：T04 Adapter 用其动态约束 + networknt 客户端校验；
    -- 播种行暂为 NULL，由 T04/T10 按各自输出形态补全。
    output_schema       JSONB CHECK (output_schema IS NULL OR jsonb_typeof(output_schema) = 'object'),
    -- 现有 AgentDefinition.toolNames 的落库形态（03/08：一期工具白名单即权限 profile）。
    tool_whitelist      JSONB NOT NULL DEFAULT '[]'::jsonb
                        CHECK (jsonb_typeof(tool_whitelist) = 'array'),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agent_definitions_slug_version UNIQUE (agent_slug, version)
);

-- 「每 slug 至多一个 active」：CREATE TABLE 不支持部分约束，用部分唯一索引下沉到 DB。
CREATE UNIQUE INDEX uq_agent_definitions_active_slug
    ON app.agent_definitions(agent_slug)
    WHERE status = 'active';

CREATE INDEX idx_agent_definitions_status ON app.agent_definitions(status);

-- ② agent_runs 加列（03/04）：run_mode 隔离草稿试跑（PREVIEW 不污染 LIVE 统计与基线）；
--    intent/provider 替代意图桥「每次运行多落一条重复 AGENT 审计」的通道（04 差异⑦）。
ALTER TABLE app.agent_runs
    ADD COLUMN run_mode VARCHAR(16) NOT NULL DEFAULT 'LIVE'
        CHECK (run_mode IN ('LIVE', 'PREVIEW')),
    ADD COLUMN intent VARCHAR(64),
    ADD COLUMN provider VARCHAR(128);

-- ③ agent_eval_cases（07）：一张表 + metric_kind 二分（INVARIANT 确定性基线 / QUALITY 参考指标）。
--    expected schema 由 metric_kind 派生（INVARIANT → tool_sequence/requires_human/missing_fields/
--    expected_error；QUALITY → answer_contains），跑分器读取时校验、非法拒跑（T03）。
CREATE TABLE app.agent_eval_cases (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_slug          VARCHAR(64) NOT NULL
                        CHECK (agent_slug ~ '^[a-z][a-z0-9-]{0,63}$'),
    agent_version       INTEGER NOT NULL CHECK (agent_version > 0),
    metric_kind         VARCHAR(16) NOT NULL CHECK (metric_kind IN ('INVARIANT', 'QUALITY')),
    input               JSONB NOT NULL,
    expected            JSONB NOT NULL CHECK (jsonb_typeof(expected) = 'object'),
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'CONFIRMED')),
    created_by          VARCHAR(128) NOT NULL CHECK (btrim(created_by) <> ''),
    confirmed_by        VARCHAR(128),
    confirmed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_eval_cases_definition
        FOREIGN KEY (agent_slug, agent_version)
        REFERENCES app.agent_definitions (agent_slug, version)
);

CREATE INDEX idx_agent_eval_cases_definition
    ON app.agent_eval_cases(agent_slug, agent_version, metric_kind);

-- ==========================================================================
-- 播种：4 个 Agent 定义（version=1, status='active'，activated_by='system' 表示迁移引导激活）。
-- 三个业务 Agent 的字段与代码 Configuration 常量逐字一致（对照测试 AgentPlatformSeedVerbatimTest）；
-- meta-agent（06）无代码定义，由本迁移首建，allow_write=true。
-- ==========================================================================

INSERT INTO app.agent_definitions (
    agent_slug, name, description, system_prompt, prompt_version, model_ref,
    enabled, version, status, activated_by, activated_at, allow_write,
    guard_exemptions, output_schema, tool_whitelist)
VALUES (
    'procurement-price-agent',
    '采购比价 Agent',
    '针对采购工单/SKU 汇总进货价、履约方映射与库存上下文，输出结构化比价建议；低置信度或信息不全时转人工。',
    $$你是采购比价 Agent（只读，绝不触发任何写操作）。你的职责：针对采购工单或 SKU 汇总进货价、履约方映射与库存上下文，输出结构化比价建议。

输入是结构化 JSON：{"procurement_ticket_id": "..."} 或 {"sku_id": "..."}，可含 {"quantity": "..."}。

工具调用序列（如适用，依序进行；信息足够时即可省略后续步骤）：
1. 输入含 procurement_ticket_id 时先调 get_procurement_ticket 获取缺口与上下文；只有 sku_id 时调 get_sku；
2. 调 search_skus 或 get_sku 获取目标 SKU 的进货价/零售价（decimal-string）；
3. 调 list_provider_skus（按 provider_id）获取各履约方外部编码与映射；
4. 调 get_inventory_overview 或 get_inventory_detail 确认可用库存。

输出规则（严格遵守 ProcurementPriceRecommendation schema）：
- target_sku 填目标 SKU 编码（如 SKU-1001）；requested_quantity 填输入数量 （decimal-string，输入未提供可为空）；
- inventory.available / inventory.shortage 为 decimal-string；无库存观测时 inventory 置 null；
- candidates 每项：provider_code 用工具返回的 provider_code；price 为 decimal-string 且最多两位小数（SCALE=2）；price_basis 只能是 sku_commercial_price（SKU 主数据进货价）或 provider_sku（履约方映射价格）；价格必须来自工具返回，严禁编造；
- 有价格可比且信息完整时：requires_human=false，recommendation 给出最低价且可信的 provider 与理由（必须来自工具事实）；
- 无候选 / 无价格 / 字段缺失 / 低置信度（confidence<0.6）/ 库存未知 时：requires_human=true，recommendation 置空，missing_fields 列出缺失项，只给出可复核的事实摘要；
- confidence 依据数据完整度与价格一致性给出 0.0-1.0 的分数。

安全约束：
- 只调用白名单内的只读工具（list_procurement_tickets / get_procurement_ticket / list_procurement_receipts / search_skus / get_sku / list_provider_skus / get_inventory_overview / get_inventory_detail / list_products / list_categories / list_fulfillment_providers），绝不调用任何写工具；
- 不发起采购、不下单、不修改任何工单；建议不落业务表。$$,
    'procurement-price-v1',
    'app.agent',
    true, 1, 'active', 'system', CURRENT_TIMESTAMP, false,
    '[]'::jsonb, NULL,
    '["list_procurement_tickets","get_procurement_ticket","list_procurement_receipts","search_skus","get_sku","list_provider_skus","get_inventory_overview","get_inventory_detail","list_products","list_categories","list_fulfillment_providers"]'::jsonb);

INSERT INTO app.agent_definitions (
    agent_slug, name, description, system_prompt, prompt_version, model_ref,
    enabled, version, status, activated_by, activated_at, allow_write,
    guard_exemptions, output_schema, tool_whitelist)
VALUES (
    'data-query-agent',
    '数据查询',
    '自然语言只读数据查询：订单/采购/SKU 价格/库存/主数据',
    $$你是数据查询助手（只读）。你只能使用下方提供的只读工具查询数据，绝不执行任何写操作。

可用工具（均只读）：
- list_procurement_tickets：采购工单摘要（状态/日期范围/分页）——缺货订单行按 procurement_status=PENDING 统计；
- get_procurement_ticket：采购工单详情（缺口 remaining_quantity、回执、关联订单行）；
- list_procurement_receipts：采购工单的全部不可变回执；
- search_skus：按商品名/规格/SKU 编号模糊检索 SKU（含进货价 purchase_price 与零售价 retail_price）；
- get_sku：单个 SKU 详情；list_provider_skus：履约方外部编码映射；
- get_inventory_overview / get_inventory_detail：库存观测；
- list_products / list_categories / list_fulfillment_providers：主数据；
- list_interpretations / list_message_media：消息解释历史与媒体元数据。

规则：
1. 只调用上述工具；未调用的信息一律不编造，数字必须来自工具返回值。
2. 信息不全或歧义（未给出具体 SKU 编号、采购工单数字 ticket_id、履约方等）时：
   不猜测参数，输出 clarification_needed 列出需要用户补充的信息，
   sources 保持空数组，requires_human=true。
3. 涉及客户/收货人/收件人姓名、手机号、地址等 PII：直接 requires_human=true
   并说明需转人工，不得调用任何工具。
4. 输出严格按给定 JSON schema：answer 是含数字的人话摘要；sources 记录实际调用过的
   工具、关键参数与 row_count；confidence 为 0~1 的置信度；clarification_needed
   无需澄清时为空数组；金额沿用工具返回的 decimal 原值，不得四舍五入丢小数。
5. 采购工单只能按数字 ticket_id 查询；工单号（如 P-123）无法解析，须请用户提供 ticket_id。$$,
    'data-query-v1',
    'app.agent',
    true, 1, 'active', 'system', CURRENT_TIMESTAMP, false,
    '[]'::jsonb, NULL,
    '["list_procurement_tickets","get_procurement_ticket","list_procurement_receipts","search_skus","get_sku","list_provider_skus","get_inventory_overview","get_inventory_detail","list_products","list_categories","list_fulfillment_providers","list_interpretations","list_message_media"]'::jsonb);

INSERT INTO app.agent_definitions (
    agent_slug, name, description, system_prompt, prompt_version, model_ref,
    enabled, version, status, activated_by, activated_at, allow_write,
    guard_exemptions, output_schema, tool_whitelist)
VALUES (
    'intent-recognition',
    '意图识别',
    '企业微信消息意图分类与分流',
    $$你是企业微信消息意图识别 Agent（单次分类接缝，无工具调用）。职责：对企业微信消息做意图分类与分流，输出六枚举意图之一（CUSTOMER_ORDER / SUPPLIER_TRACKING / ORDER_CHANGE / ORDER_CANCEL / NON_BUSINESS / NEED_REVIEW）。

实际执行由既有消息解释管线（MessageInterpreter / DeepSeekMessageInterpreter，提示词引用既有 PROMPT_V1 语义，版本见 app.message-interpreter.prompt-version）完成；本定义仅将意图识别注册为受管 Agent，获得统一启停视图与运行观测，不改变既有分流行为，不替代既有 MessageInterpretation 持久化。$$,
    'intent-recognition-v1',
    'app.message-interpreter',
    true, 1, 'active', 'system', CURRENT_TIMESTAMP, false,
    '[]'::jsonb, NULL,
    '[]'::jsonb);

INSERT INTO app.agent_definitions (
    agent_slug, name, description, system_prompt, prompt_version, model_ref,
    enabled, version, status, activated_by, activated_at, allow_write,
    guard_exemptions, output_schema, tool_whitelist)
VALUES (
    'meta-agent',
    '元 Agent',
    '用自然语言创建/修改受管 Agent 的定义草稿与建议评测输入（只能写草稿，经人工确认后启用）',
    $$你是元 Agent（meta-agent）：用自然语言帮助运营人员创建或修改受管 Agent 的定义草稿。你只能产出「草稿 JSON」作为输出，绝不直接启用任何 Agent，也无权启停其他 Agent。

输入：用户用自然语言描述想要创建的 Agent（职责、系统提示词要点、可用工具、模型偏好）或对现有 Agent 的修改意图。

输出（严格遵守草稿 JSON schema）：
- agent_slug：^[a-z][a-z0-9-]{0,63}$ 的小写 slug（新 Agent 由你按职责命名；与现有 slug 冲突时必须向用户说明并请求确认，不得擅自改名）；
- name / description / system_prompt / prompt_version / model_ref / enabled / tool_whitelist：定义全量字段；
- allow_write：默认 false，仅在用户明确要求且职责确实需要写操作时置 true；
- suggested_eval_cases：建议的评测输入（自然语言样例列表，供 INVARIANT/QUALITY 评测使用）。

规则：
1. 关键信息不足（职责不清、工具范围不明、slug 冲突未决）时：输出 NEEDS_INPUT 与明确的澄清问题，绝不猜测填充；
2. 你只能写草稿；启用必须经人工确认；禁止修改 meta-agent 自身的定义；
3. 涉及密钥/凭据的内容一律拒绝，并要求通过环境变量配置。$$,
    'meta-agent-v1',
    'app.agent',
    true, 1, 'active', 'system', CURRENT_TIMESTAMP, true,
    '[]'::jsonb, NULL,
    '["list_agent_tools","create_agent_draft","update_agent_draft"]'::jsonb);

-- ==========================================================================
-- 播种：14 例 INVARIANT 评测用例（CONFIRMED）。
-- 来源：procurement-eval-v1 7 例（ProcurementPriceEvalFixture）+ data-query-eval-v1 7 条
-- （DataQueryAgentEvalFixture）。expected 按 07 的 INVARIANT 派生 schema：
-- tool_sequence / requires_human / missing_fields / expected_error（负例）。
-- ==========================================================================

-- procurement-price-agent / version 1（7 例）
INSERT INTO app.agent_eval_cases (
    agent_slug, agent_version, metric_kind, input, expected, status, created_by, confirmed_by, confirmed_at)
VALUES
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"procurement_ticket_id":"9001","quantity":"2"}'::jsonb,
     '{"requires_human":false}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"sku_id":"1001"}'::jsonb,
     '{"requires_human":false}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"procurement_ticket_id":"9002","quantity":"1"}'::jsonb,
     '{"requires_human":true,"missing_fields":["candidates"]}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"procurement_ticket_id":"9003"}'::jsonb,
     '{"requires_human":true,"missing_fields":["price"]}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"procurement_ticket_id":"9004","quantity":"4"}'::jsonb,
     '{"requires_human":true,"missing_fields":["provider_sku_name"]}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"sku_id":"1001"}'::jsonb,
     '{"requires_human":false}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('procurement-price-agent', 1, 'INVARIANT',
     '{"sku_id":"1002"}'::jsonb,
     '{"expected_error":"AGENT_OUTPUT_INVALID"}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP);

-- data-query-agent / version 1（7 条：3 可答 + 3 澄清 + 1 PII 转人工）
INSERT INTO app.agent_eval_cases (
    agent_slug, agent_version, metric_kind, input, expected, status, created_by, confirmed_by, confirmed_at)
VALUES
    ('data-query-agent', 1, 'INVARIANT',
     '"最近 7 天有多少缺货的订单行"'::jsonb,
     '{"requires_human":false,"tool_sequence":["list_procurement_tickets"]}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('data-query-agent', 1, 'INVARIANT',
     '"SKU-xxx 的进货价和零售价是多少"'::jsonb,
     '{"requires_human":true}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('data-query-agent', 1, 'INVARIANT',
     '"采购工单 P-123 还差多少数量"'::jsonb,
     '{"requires_human":true}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('data-query-agent', 1, 'INVARIANT',
     '"某履约方本月共接收多少运单回执"'::jsonb,
     '{"requires_human":true}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('data-query-agent', 1, 'INVARIANT',
     '"SKU-EVAL-000001 的进货价和零售价是多少"'::jsonb,
     '{"requires_human":false,"tool_sequence":["search_skus"]}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('data-query-agent', 1, 'INVARIANT',
     '"采购工单 9005 还差多少数量"'::jsonb,
     '{"requires_human":false,"tool_sequence":["get_procurement_ticket"]}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP),
    ('data-query-agent', 1, 'INVARIANT',
     '"查一下客户张三的收货地址"'::jsonb,
     '{"requires_human":true}'::jsonb,
     'CONFIRMED', 'system', 'system', CURRENT_TIMESTAMP);
