-- 中汇 PMS 批量上传批次（api-contract §3.5：外部交互先持久化意图/批次，再由 Adapter 执行并回写结果）。
-- 批次先以 PENDING 落库（含逐商品 PENDING 行），逐商品调用中汇创建商品后回写 SUCCESS/FAILED
-- （含 goodsId 商品列表校验结果与 warning 非阻断提示），最后批次置 COMPLETED。
-- 中途断连时 PENDING 行即为可恢复/可审计的意图记录；本表非业务订单表，仅供 PMS 上传作业追踪。

CREATE TABLE app.zhonghui_pms_upload_batches (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no      VARCHAR(32) NOT NULL UNIQUE,
    status        VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED')),
    total         INTEGER NOT NULL DEFAULT 0 CHECK (total >= 0),
    succeeded     INTEGER NOT NULL DEFAULT 0 CHECK (succeeded >= 0),
    failed        INTEGER NOT NULL DEFAULT 0 CHECK (failed >= 0),
    created_by    VARCHAR(128) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at  TIMESTAMPTZ
);

CREATE TABLE app.zhonghui_pms_upload_batch_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        BIGINT NOT NULL REFERENCES app.zhonghui_pms_upload_batches(id) ON DELETE CASCADE,
    sku_id          BIGINT NOT NULL,
    sku_code        VARCHAR(64),
    goods_name      VARCHAR(300),
    status          VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    business_code   VARCHAR(64),
    message         TEXT,
    goods_id        BIGINT,
    pms_status      VARCHAR(64),
    warning         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_zhonghui_pms_upload_batch_items_batch
    ON app.zhonghui_pms_upload_batch_items (batch_id);
