-- ===========================================================================
-- V39: 静态礼包 BOM 主数据（static-bundle-bom 02 票定稿 DDL）
-- 礼包 = product_bundles(商品族属性) + bundle_items(组件清单)
-- 礼包本身不创建 internal_sku、不单独计库存；订单命中时下单快照 BOM 到
-- order_line_components，主数据后续修改不影响历史订单。
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1) 礼包主表
-- ---------------------------------------------------------------------------
CREATE TABLE app.product_bundles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_code         VARCHAR(64) NOT NULL UNIQUE,
    bundle_name         VARCHAR(200) NOT NULL,
    category_id         BIGINT REFERENCES app.categories(id) ON DELETE RESTRICT,
    barcode             VARCHAR(64) UNIQUE,
    description         TEXT,
    tax_rate            NUMERIC(5, 2),
    settlement_cost     NUMERIC(14, 2),
    -- 礼包级履约方：由 bundle_items 触发器推导维护；NULL=组件未齐
    fulfillment_provider_id BIGINT REFERENCES app.fulfillment_providers(id) ON DELETE RESTRICT,
    -- 上架状态：DRAFT=组件未齐不可被订单命中；ACTIVE=可识别命中；INACTIVE=下架
    status              VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
                        CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
    lock_version        BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (btrim(bundle_code) <> ''),
    CHECK (btrim(bundle_name) <> ''),
    CHECK (barcode IS NULL OR btrim(barcode) <> ''),
    CHECK (tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 100)),
    CHECK (settlement_cost IS NULL OR settlement_cost >= 0)
);

-- ---------------------------------------------------------------------------
-- 2) 组件表
-- ---------------------------------------------------------------------------
CREATE TABLE app.bundle_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id           BIGINT NOT NULL REFERENCES app.product_bundles(id) ON DELETE RESTRICT,
    sort_no             INTEGER NOT NULL CHECK (sort_no > 0),
    sku_id              BIGINT NOT NULL REFERENCES app.skus(id) ON DELETE RESTRICT,
    quantity_per_bundle NUMERIC(18,3) NOT NULL
                        CHECK (quantity_per_bundle > 0
                               AND trunc(quantity_per_bundle) = quantity_per_bundle),
    -- 来源文件中的京东商品编号快照；缺 EMG = NULL（权威编码在 provider_skus.provider_sku_code）
    emg_code_snapshot   VARCHAR(64),
    -- "内配"原文，供匹配与复核（01 票输入）
    source_text_snapshot VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (bundle_id, sort_no),
    UNIQUE (bundle_id, sku_id),
    CHECK (emg_code_snapshot IS NULL OR btrim(emg_code_snapshot) <> ''),
    CHECK (source_text_snapshot IS NULL OR btrim(source_text_snapshot) <> '')
);

-- ---------------------------------------------------------------------------
-- 3) 别名/识别表（镜像 sku_aliases；只用于识别建议，不自动建立业务映射）
-- ---------------------------------------------------------------------------
CREATE TABLE app.bundle_aliases (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id           BIGINT NOT NULL REFERENCES app.product_bundles(id) ON DELETE RESTRICT,
    alias_type          VARCHAR(32) NOT NULL
                        CHECK (alias_type IN ('NAME', 'BARCODE', 'SPECIFICATION', 'OTHER')),
    alias_value         VARCHAR(255) NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (bundle_id, alias_type, alias_value),
    CHECK (btrim(alias_value) <> '')
);

-- ---------------------------------------------------------------------------
-- 4) order_lines 增加 bundle_id（静态礼包命中时非空；当单定制仍为 NULL）
-- ---------------------------------------------------------------------------
ALTER TABLE app.order_lines
    ADD COLUMN bundle_id BIGINT REFERENCES app.product_bundles(id) ON DELETE RESTRICT;

ALTER TABLE app.order_lines
    ADD CONSTRAINT order_lines_bundle_single_only
    CHECK (line_type <> 'SINGLE' OR bundle_id IS NULL);

-- ---------------------------------------------------------------------------
-- 5) 触发器函数
-- ---------------------------------------------------------------------------

-- 5.1 组件写入：数量正整数（列 CHECK 兜底）+ 推导/校验礼包履约方
CREATE FUNCTION app.validate_bundle_item() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    sku_provider_id BIGINT;
    bundle_provider_id BIGINT;
BEGIN
    SELECT fulfillment_provider_id INTO STRICT sku_provider_id
    FROM app.skus WHERE id = NEW.sku_id;

    IF sku_provider_id IS NULL THEN
        RAISE EXCEPTION 'bundle component SKU must have a fulfillment provider';
    END IF;

    SELECT fulfillment_provider_id INTO bundle_provider_id
    FROM app.product_bundles WHERE id = NEW.bundle_id;

    IF bundle_provider_id IS NULL THEN
        -- 首个组件：把礼包履约方定为该组件 SKU 的履约方
        UPDATE app.product_bundles
           SET fulfillment_provider_id = sku_provider_id
         WHERE id = NEW.bundle_id;
    ELSIF bundle_provider_id <> sku_provider_id THEN
        RAISE EXCEPTION 'all bundle components must belong to one fulfillment provider';
    END IF;
    RETURN NEW;
END;
$$;

-- 5.2 礼包状态：ACTIVE 前置条件（至少一个组件）
CREATE FUNCTION app.validate_bundle_status() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'ACTIVE' AND NOT EXISTS (
        SELECT 1 FROM app.bundle_items WHERE bundle_id = NEW.id
    ) THEN
        RAISE EXCEPTION 'active bundle requires at least one component';
    END IF;
    RETURN NEW;
END;
$$;

-- 5.3 order_lines.bundle_id 引用校验
CREATE FUNCTION app.validate_order_line_bundle_ref() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    bundle_status_value VARCHAR(16);
BEGIN
    IF NEW.line_type = 'SINGLE' AND NEW.bundle_id IS NOT NULL THEN
        RAISE EXCEPTION 'single order line cannot reference a bundle';
    END IF;
    IF NEW.bundle_id IS NOT NULL THEN
        SELECT status INTO STRICT bundle_status_value
        FROM app.product_bundles WHERE id = NEW.bundle_id;
        IF bundle_status_value <> 'ACTIVE' THEN
            RAISE EXCEPTION 'order line can only reference an ACTIVE bundle';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

-- 5.4 静态礼包快照一致性：父行 bundle_id 非空时，组件须与主数据当前 BOM 一致
CREATE FUNCTION app.validate_static_bundle_snapshot() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    parent_bundle_id BIGINT;
    matched BOOLEAN;
BEGIN
    SELECT bundle_id INTO parent_bundle_id
    FROM app.order_lines WHERE id = NEW.order_line_id;

    IF parent_bundle_id IS NOT NULL THEN
        SELECT EXISTS (
            SELECT 1 FROM app.bundle_items
            WHERE bundle_id = parent_bundle_id
              AND sku_id = NEW.sku_id
              AND quantity_per_bundle = NEW.quantity_per_bundle
        ) INTO matched;
        IF NOT matched THEN
            RAISE EXCEPTION 'static bundle snapshot does not match bundle master BOM';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

-- 5.5 礼包删除保护（FK RESTRICT 已挡，此触发器统一报错文案）
CREATE FUNCTION app.protect_bundle_delete() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'bundle referenced by orders or components cannot be deleted';
END;
$$;

CREATE TRIGGER trg_bundle_item_validation
BEFORE INSERT OR UPDATE ON app.bundle_items
FOR EACH ROW EXECUTE FUNCTION app.validate_bundle_item();

CREATE TRIGGER trg_bundle_status_validation
BEFORE INSERT OR UPDATE ON app.product_bundles
FOR EACH ROW EXECUTE FUNCTION app.validate_bundle_status();

CREATE TRIGGER trg_order_line_bundle_ref
BEFORE INSERT OR UPDATE ON app.order_lines
FOR EACH ROW EXECUTE FUNCTION app.validate_order_line_bundle_ref();

CREATE TRIGGER trg_static_bundle_snapshot
BEFORE INSERT OR UPDATE ON app.order_line_components
FOR EACH ROW EXECUTE FUNCTION app.validate_static_bundle_snapshot();

CREATE TRIGGER trg_bundle_delete_protection
BEFORE DELETE ON app.product_bundles
FOR EACH ROW EXECUTE FUNCTION app.protect_bundle_delete();

-- 5.6 set_updated_at 循环数组追加（与 V1 基线同款 DO 块）
DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'product_bundles', 'bundle_items', 'bundle_aliases'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON app.%I FOR EACH ROW EXECUTE FUNCTION app.set_updated_at()',
            'trg_' || table_name || '_updated_at', table_name
        );
    END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- 6) 索引
-- ---------------------------------------------------------------------------
CREATE INDEX idx_bundle_items_bundle ON app.bundle_items(bundle_id);
CREATE INDEX idx_bundle_items_sku ON app.bundle_items(sku_id);
CREATE INDEX idx_bundle_aliases_value ON app.bundle_aliases(alias_type, alias_value) WHERE active;
CREATE INDEX idx_order_lines_bundle ON app.order_lines(bundle_id) WHERE bundle_id IS NOT NULL;
