-- V41: 万齐来源渠道 + 静态礼包显式映射。
-- 万齐订单表是独立来源渠道；来源礼包编号只能显式指向已 ACTIVE 的静态礼包。

ALTER TABLE app.customer_source_refs DROP CONSTRAINT customer_source_refs_source_channel_check;
ALTER TABLE app.customer_source_refs ADD CONSTRAINT customer_source_refs_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.source_channel_skus DROP CONSTRAINT source_channel_skus_source_channel_check;
ALTER TABLE app.source_channel_skus ADD CONSTRAINT source_channel_skus_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.import_batches DROP CONSTRAINT import_batches_source_channel_check;
ALTER TABLE app.import_batches ADD CONSTRAINT import_batches_source_channel_check
    CHECK (source_channel IS NULL OR source_channel IN
           ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.orders DROP CONSTRAINT orders_source_channel_check;
ALTER TABLE app.orders ADD CONSTRAINT orders_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.shipment_syncs DROP CONSTRAINT shipment_syncs_source_channel_check;
ALTER TABLE app.shipment_syncs ADD CONSTRAINT shipment_syncs_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.connector_configs DROP CONSTRAINT connector_configs_source_channel_check;
ALTER TABLE app.connector_configs ADD CONSTRAINT connector_configs_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

INSERT INTO app.connector_configs (source_channel, config) VALUES
    ('WANGQI', '{"carrier_mappings":{"JD":"京东物流"}}'::JSONB);

CREATE TABLE app.source_channel_bundles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_channel      VARCHAR(32) NOT NULL
                        CHECK (source_channel IN
                               ('CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM')),
    source_bundle_ref   VARCHAR(128) NOT NULL,
    source_bundle_name  VARCHAR(255),
    source_barcode      VARCHAR(128),
    quantity_multiplier NUMERIC(18,3) NOT NULL DEFAULT 1
                        CHECK (quantity_multiplier = 1),
    bundle_id           BIGINT NOT NULL REFERENCES app.product_bundles(id) ON DELETE RESTRICT,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    lock_version        BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_channel, source_bundle_ref),
    CHECK (btrim(source_bundle_ref) <> ''),
    CHECK (source_bundle_name IS NULL OR btrim(source_bundle_name) <> ''),
    CHECK (source_barcode IS NULL OR btrim(source_barcode) <> '')
);

CREATE UNIQUE INDEX uq_source_channel_bundles_barcode
    ON app.source_channel_bundles(source_channel, source_barcode)
    WHERE source_barcode IS NOT NULL;
CREATE INDEX idx_source_channel_bundles_bundle
    ON app.source_channel_bundles(bundle_id);

CREATE FUNCTION app.validate_source_channel_bundle() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    bundle_status_value VARCHAR(16);
BEGIN
    SELECT status INTO STRICT bundle_status_value
    FROM app.product_bundles
    WHERE id = NEW.bundle_id;

    IF bundle_status_value <> 'ACTIVE' THEN
        RAISE EXCEPTION 'source bundle mapping requires an ACTIVE bundle';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_source_channel_bundle_validation
BEFORE INSERT OR UPDATE ON app.source_channel_bundles
FOR EACH ROW EXECUTE FUNCTION app.validate_source_channel_bundle();

CREATE TRIGGER trg_source_channel_bundles_updated_at
BEFORE UPDATE ON app.source_channel_bundles
FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();
