-- 追加式来源归因纠正：历史批次/订单/原始行不改写，有效归因取最新纠正。

ALTER TABLE app.customer_source_refs DROP CONSTRAINT customer_source_refs_source_channel_check;
ALTER TABLE app.customer_source_refs ADD CONSTRAINT customer_source_refs_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.source_channel_skus DROP CONSTRAINT source_channel_skus_source_channel_check;
ALTER TABLE app.source_channel_skus ADD CONSTRAINT source_channel_skus_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.import_batches DROP CONSTRAINT import_batches_source_channel_check;
ALTER TABLE app.import_batches ADD CONSTRAINT import_batches_source_channel_check
    CHECK (source_channel IS NULL OR source_channel IN
           ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.orders DROP CONSTRAINT orders_source_channel_check;
ALTER TABLE app.orders ADD CONSTRAINT orders_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.shipment_syncs DROP CONSTRAINT shipment_syncs_source_channel_check;
ALTER TABLE app.shipment_syncs ADD CONSTRAINT shipment_syncs_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.connector_configs DROP CONSTRAINT connector_configs_source_channel_check;
ALTER TABLE app.connector_configs ADD CONSTRAINT connector_configs_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

ALTER TABLE app.source_channel_bundles DROP CONSTRAINT source_channel_bundles_source_channel_check;
ALTER TABLE app.source_channel_bundles ADD CONSTRAINT source_channel_bundles_source_channel_check
    CHECK (source_channel IN ('CAISHIXIAN', 'DAZHE', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI', 'WANGQI', 'WECOM'));

INSERT INTO app.connector_configs (source_channel, enabled, mode, transport_mode, config)
SELECT 'DAZHE', enabled, mode, transport_mode, config
FROM app.connector_configs WHERE source_channel='WANGQI'
ON CONFLICT (source_channel) DO NOTHING;

INSERT INTO app.source_channel_skus
    (source_channel, source_sku_ref, source_product_name, source_specification,
     quantity_multiplier, sku_id, active)
SELECT 'DAZHE', source_sku_ref, source_product_name, source_specification,
       quantity_multiplier, sku_id, active
FROM app.source_channel_skus WHERE source_channel='WANGQI'
ON CONFLICT (source_channel, source_sku_ref) DO NOTHING;

INSERT INTO app.source_channel_bundles
    (source_channel, source_bundle_ref, source_bundle_name, source_barcode,
     quantity_multiplier, bundle_id, active)
SELECT 'DAZHE', source_bundle_ref, source_bundle_name, source_barcode,
       quantity_multiplier, bundle_id, active
FROM app.source_channel_bundles WHERE source_channel='WANGQI'
ON CONFLICT (source_channel, source_bundle_ref) DO NOTHING;

CREATE TABLE app.source_attribution_corrections (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id                 BIGINT NOT NULL REFERENCES app.import_batches(id) ON DELETE RESTRICT,
    correction_no                   INTEGER NOT NULL CHECK (correction_no > 0),
    attributed_source_channel       VARCHAR(32) NOT NULL
                                      CONSTRAINT source_attribution_corrections_channel_check
                                      CHECK (attributed_source_channel IN ('DAZHE', 'WANGQI')),
    attributed_template_family      VARCHAR(128) NOT NULL,
    attributed_template_fingerprint VARCHAR(128) NOT NULL,
    reason                          VARCHAR(500) NOT NULL,
    evidence                        JSONB NOT NULL DEFAULT '{}'::JSONB
                                      CHECK (jsonb_typeof(evidence) = 'object'),
    corrected_by                    VARCHAR(128) NOT NULL,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (import_batch_id, correction_no),
    CHECK (btrim(attributed_template_family) <> ''),
    CHECK (btrim(attributed_template_fingerprint) <> ''),
    CHECK (btrim(reason) <> ''),
    CHECK (btrim(corrected_by) <> '')
);

CREATE TABLE app.source_return_export_invalidations (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_return_export_id         BIGINT NOT NULL UNIQUE
                                      REFERENCES app.source_return_exports(id) ON DELETE RESTRICT,
    source_attribution_correction_id BIGINT NOT NULL
                                      REFERENCES app.source_attribution_corrections(id) ON DELETE RESTRICT,
    reason_code                     VARCHAR(64) NOT NULL,
    invalidated_by                  VARCHAR(128) NOT NULL,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (btrim(reason_code) <> ''),
    CHECK (btrim(invalidated_by) <> '')
);

-- 旧索引把已失效历史版本也计作 final；改为在批次锁内只拒绝第二个“有效 final”。
DROP INDEX app.uq_source_return_final_per_batch;

CREATE INDEX idx_source_attribution_corrections_batch
    ON app.source_attribution_corrections(import_batch_id, correction_no DESC);

CREATE FUNCTION app.validate_source_attribution_correction() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    recorded_channel VARCHAR(32);
    previous_channel VARCHAR(32);
    expected_no INTEGER;
BEGIN
    SELECT source_channel INTO STRICT recorded_channel
    FROM app.import_batches
    WHERE id=NEW.import_batch_id AND batch_type='SOURCE_ORDER'
    FOR UPDATE;

    SELECT attributed_source_channel INTO previous_channel
    FROM app.source_attribution_corrections
    WHERE import_batch_id=NEW.import_batch_id
    ORDER BY correction_no DESC LIMIT 1;

    SELECT COALESCE(MAX(correction_no), 0)+1 INTO expected_no
    FROM app.source_attribution_corrections WHERE import_batch_id=NEW.import_batch_id;

    IF NEW.correction_no <> expected_no THEN
        RAISE EXCEPTION 'source attribution correction_no must be sequential';
    END IF;
    IF NEW.attributed_source_channel = COALESCE(previous_channel, recorded_channel) THEN
        RAISE EXCEPTION 'source attribution correction must change the effective channel';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION app.validate_source_return_invalidation() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    export_batch_id BIGINT;
    correction_batch_id BIGINT;
    export_push_status VARCHAR(16);
BEGIN
    SELECT import_batch_id, push_status INTO STRICT export_batch_id, export_push_status
    FROM app.source_return_exports WHERE id=NEW.source_return_export_id;
    SELECT import_batch_id INTO STRICT correction_batch_id
    FROM app.source_attribution_corrections WHERE id=NEW.source_attribution_correction_id;

    IF export_batch_id <> correction_batch_id THEN
        RAISE EXCEPTION 'source return invalidation must use a correction from the same import batch';
    END IF;
    IF export_push_status IN ('PUSHING', 'SUCCESS') THEN
        RAISE EXCEPTION 'a pushing or pushed source return export cannot be invalidated';
    END IF;
    RETURN NEW;
END;
$$;

CREATE FUNCTION app.validate_single_valid_final_source_return() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    -- 替代旧唯一索引后仍需由数据库串行化同批次 final 判定，避免并发双 final。
    PERFORM 1 FROM app.import_batches WHERE id=NEW.import_batch_id FOR UPDATE;
    IF NEW.is_final AND EXISTS (
        SELECT 1 FROM app.source_return_exports existing
        WHERE existing.import_batch_id=NEW.import_batch_id AND existing.is_final
          AND NOT EXISTS (
              SELECT 1 FROM app.source_return_export_invalidations invalidation
              WHERE invalidation.source_return_export_id=existing.id)
    ) THEN
        RAISE EXCEPTION 'source order batch already has a valid final return export';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_source_attribution_correction_validation
BEFORE INSERT ON app.source_attribution_corrections
FOR EACH ROW EXECUTE FUNCTION app.validate_source_attribution_correction();

CREATE TRIGGER trg_source_attribution_correction_append_only
BEFORE UPDATE OR DELETE ON app.source_attribution_corrections
FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();

CREATE TRIGGER trg_source_return_invalidation_validation
BEFORE INSERT ON app.source_return_export_invalidations
FOR EACH ROW EXECUTE FUNCTION app.validate_source_return_invalidation();

CREATE TRIGGER trg_source_return_invalidation_append_only
BEFORE UPDATE OR DELETE ON app.source_return_export_invalidations
FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();

CREATE TRIGGER trg_source_return_single_valid_final
BEFORE INSERT ON app.source_return_exports
FOR EACH ROW EXECUTE FUNCTION app.validate_single_valid_final_source_return();

CREATE VIEW app.v_import_batch_effective_source AS
SELECT ib.id AS import_batch_id,
       ib.source_channel AS recorded_source_channel,
       COALESCE(c.attributed_source_channel, ib.source_channel) AS effective_source_channel,
       ib.template_family AS recorded_template_family,
       COALESCE(c.attributed_template_family, ib.template_family) AS effective_template_family,
       ib.template_fingerprint AS recorded_template_fingerprint,
       COALESCE(c.attributed_template_fingerprint, ib.template_fingerprint) AS effective_template_fingerprint,
       c.id AS latest_correction_id,
       c.correction_no AS latest_correction_no
FROM app.import_batches ib
LEFT JOIN LATERAL (
    SELECT id, correction_no, attributed_source_channel,
           attributed_template_family, attributed_template_fingerprint
    FROM app.source_attribution_corrections
    WHERE import_batch_id=ib.id
    ORDER BY correction_no DESC LIMIT 1
) c ON TRUE;

-- 回填行的快递映射也必须以有效归因为准；其余不可变血缘校验保持 V1 口径。
CREATE OR REPLACE FUNCTION app.validate_source_return_item() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    export_batch_id BIGINT;
    raw_batch_id BIGINT;
    raw_order_id BIGINT;
    raw_line_id BIGINT;
    order_scope VARCHAR(16);
    shipment_order_id BIGINT;
    shipment_sequence_value INTEGER;
    tracking_code VARCHAR(64);
    tracking_name VARCHAR(128);
    tracking_number_value VARCHAR(128);
    source_channel_value VARCHAR(32);
    mapped_logistics_company TEXT;
    shipped_quantity_value NUMERIC(18,3);
    fulfillment_outcome_value VARCHAR(32);
    cancelled_quantity_value NUMERIC(18,3);
BEGIN
    SELECT sre.import_batch_id, source.effective_source_channel
    INTO STRICT export_batch_id, source_channel_value
    FROM app.source_return_exports sre
    JOIN app.v_import_batch_effective_source source ON source.import_batch_id=sre.import_batch_id
    WHERE sre.id = NEW.source_return_export_id;
    SELECT import_batch_id, order_id, order_line_id
    INTO STRICT raw_batch_id, raw_order_id, raw_line_id
    FROM app.raw_import_rows WHERE id = NEW.raw_import_row_id;

    IF raw_batch_id <> export_batch_id THEN
        RAISE EXCEPTION 'source return raw row belongs to another import batch';
    END IF;
    IF NEW.order_line_id IS DISTINCT FROM raw_line_id THEN
        RAISE EXCEPTION 'source return order line must equal the raw-row mapping';
    END IF;

    IF raw_order_id IS NOT NULL THEN
        SELECT data_scope INTO STRICT order_scope FROM app.orders WHERE id = raw_order_id;
        IF order_scope <> 'BUSINESS' THEN
            RAISE EXCEPTION 'source return exports may contain only BUSINESS orders';
        END IF;
    END IF;
    IF NEW.order_line_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM app.order_lines
        WHERE id = NEW.order_line_id AND order_id = raw_order_id
    ) THEN
        RAISE EXCEPTION 'source return raw row and order line belong to different orders';
    END IF;

    IF NEW.item_result = 'FILLED' THEN
        IF NEW.order_line_id IS NULL THEN
            RAISE EXCEPTION 'filled source return item requires a mapped order line';
        END IF;
        SELECT s.order_id, s.shipment_sequence,
               t.logistics_company_code, t.logistics_company_name, t.tracking_number,
               si.shipped_quantity, f.outcome, f.cancelled_quantity
        INTO STRICT shipment_order_id, shipment_sequence_value,
                    tracking_code, tracking_name, tracking_number_value,
                    shipped_quantity_value, fulfillment_outcome_value, cancelled_quantity_value
        FROM app.shipments s
        JOIN app.trackings t ON t.shipment_id = s.id
        JOIN app.shipment_items si ON si.shipment_id = s.id
        JOIN app.fulfillments f ON f.id = si.fulfillment_id
        WHERE s.id = NEW.shipment_id
          AND f.order_line_id = NEW.order_line_id;

        SELECT config #>> ARRAY['carrier_mappings', tracking_code]
        INTO mapped_logistics_company
        FROM app.connector_configs
        WHERE source_channel = source_channel_value;

        IF mapped_logistics_company IS NULL OR btrim(mapped_logistics_company) = '' THEN
            RAISE EXCEPTION 'source return carrier mapping is missing for channel % and carrier %',
                source_channel_value, tracking_code;
        END IF;

        IF shipment_order_id <> raw_order_id
           OR NEW.shipment_sequence <> shipment_sequence_value
           OR NEW.tracking_number <> tracking_number_value
           OR NEW.logistics_company <> mapped_logistics_company
           OR NEW.shipped_quantity IS DISTINCT FROM shipped_quantity_value
           OR NEW.fulfillment_outcome IS DISTINCT FROM fulfillment_outcome_value
           OR NEW.cancelled_quantity IS DISTINCT FROM cancelled_quantity_value THEN
            RAISE EXCEPTION 'source return shipment/tracking snapshot does not match its order line';
        END IF;
    ELSIF NEW.item_result = 'CANCELLED' THEN
        SELECT outcome, cancelled_quantity
        INTO STRICT fulfillment_outcome_value, cancelled_quantity_value
        FROM app.fulfillments WHERE order_line_id = NEW.order_line_id;
        IF fulfillment_outcome_value <> 'CANCELLED'
           OR NEW.fulfillment_outcome <> fulfillment_outcome_value
           OR NEW.cancelled_quantity IS DISTINCT FROM cancelled_quantity_value THEN
            RAISE EXCEPTION 'cancelled source return item does not match terminal fulfillment';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION app.validate_import_revision() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    parent_row app.import_batches%ROWTYPE;
    parent_effective_channel VARCHAR(32);
    parent_effective_family VARCHAR(128);
    export_provider_id BIGINT;
BEGIN
    IF NEW.batch_type = 'PROVIDER_TRACKING' THEN
        SELECT fulfillment_provider_id INTO STRICT export_provider_id
        FROM app.fulfillment_exports
        WHERE id = NEW.source_fulfillment_export_id;
        IF export_provider_id <> NEW.fulfillment_provider_id THEN
            RAISE EXCEPTION 'tracking import provider must match its source fulfillment export';
        END IF;
    END IF;

    IF NEW.import_mode = 'REVISION' THEN
        SELECT * INTO STRICT parent_row
        FROM app.import_batches WHERE id = NEW.parent_import_batch_id;
        SELECT effective_source_channel, effective_template_family
        INTO STRICT parent_effective_channel, parent_effective_family
        FROM app.v_import_batch_effective_source WHERE import_batch_id=parent_row.id;

        IF NEW.batch_type <> parent_row.batch_type
           OR NEW.source_channel IS DISTINCT FROM parent_effective_channel
           OR NEW.fulfillment_provider_id IS DISTINCT FROM parent_row.fulfillment_provider_id
           OR NEW.source_fulfillment_export_id IS DISTINCT FROM parent_row.source_fulfillment_export_id
           OR NEW.template_family <> parent_effective_family THEN
            RAISE EXCEPTION 'revision must preserve effective source/provider and template family';
        END IF;
        IF NEW.revision_no <> parent_row.revision_no + 1 THEN
            RAISE EXCEPTION 'revision_no must equal parent revision_no + 1';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

INSERT INTO app.order_event_types (code, display_name) VALUES
    ('SOURCE_ATTRIBUTION_CORRECTED', '来源归因已纠正');
