-- Issue #84：第三方履约导出 → 企微群自动发送 + 可手动重发 + 周期回传提醒。
--
-- 深模块（docs/agents/wecom-outbound-send.md）：一张导出状态表 + 一张 delivery 证据表。
-- - 状态表：每第三方导出唯一一行，持久化 provider/chat 路由证据、SLA/提醒间隔快照、
--   initial sent_at（= 文件消息 aibot_send_msg 成功 ack 时刻）、tracking_due_at、
--   next_reminder_at / last_reminded_at / reminder_count，以及终态
--   PENDING / ACTIVE / COMPLETED / MANUALLY_STOPPED / FAILED / UNKNOWN / LEGACY。
-- - delivery 表：每次 initial/reminder 尝试的证据（PENDING→SENDING→SENT/FAILED/UNKNOWN），
--   UNIQUE (export_id, kind, sequence) 保证同一 initial 或同一 reminder sequence
--   不会重复入队/并发发送；不持久化 media_id（3 天临时引用）或文件内容，只存摘要。
-- - 迁移安全默认：历史第三方导出登记为 LEGACY 终态，绝不自动入队、绝不部署后补发。

-- ① 旧 tracking_due_at（generated_at 派生）对新第三方导出不再是公开权威：
--    发送 ack 前为 NULL（API/UI 不得展示假的「已到期时间」），历史/JD 行保持既有语义。
ALTER TABLE app.fulfillment_exports ALTER COLUMN tracking_due_at DROP NOT NULL;

-- ② 每第三方导出一行出站/提醒状态
CREATE TABLE app.fulfillment_export_wecom_states (
    export_id                BIGINT PRIMARY KEY
                             REFERENCES app.fulfillment_exports(id) ON DELETE RESTRICT,
    provider_id              BIGINT NOT NULL
                             REFERENCES app.fulfillment_providers(id) ON DELETE RESTRICT,
    status                   VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                             CHECK (status IN (
                                 'PENDING', 'ACTIVE', 'COMPLETED', 'MANUALLY_STOPPED',
                                 'FAILED', 'UNKNOWN', 'LEGACY')),
    chat_id                  VARCHAR(128),
    tracking_sla_minutes     INTEGER NOT NULL CHECK (tracking_sla_minutes > 0),
    reminder_interval_minutes INTEGER NOT NULL CHECK (reminder_interval_minutes > 0),
    initial_sent_at          TIMESTAMPTZ,
    tracking_due_at          TIMESTAMPTZ,
    next_reminder_at         TIMESTAMPTZ,
    last_reminded_at         TIMESTAMPTZ,
    reminder_count           INTEGER NOT NULL DEFAULT 0 CHECK (reminder_count >= 0),
    last_error               VARCHAR(512),
    stopped_by               VARCHAR(128),
    stopped_reason           TEXT,
    stopped_at               TIMESTAMPTZ,
    lock_version             BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (chat_id IS NULL OR btrim(chat_id) <> ''),
    -- ACTIVE 由 initial 成功 ack 进入：计时起点、due 与快照群必须齐备
    CHECK ((status <> 'ACTIVE') OR (
        initial_sent_at IS NOT NULL AND tracking_due_at IS NOT NULL AND chat_id IS NOT NULL)),
    -- 收齐后不再自动提醒
    CHECK ((status <> 'COMPLETED') OR next_reminder_at IS NULL),
    -- 人工停止必须留证据
    CHECK ((status <> 'MANUALLY_STOPPED') OR (stopped_by IS NOT NULL AND stopped_at IS NOT NULL)),
    -- 历史导出安全默认：从未发送
    CHECK ((status <> 'LEGACY') OR initial_sent_at IS NULL),
    -- next_reminder_at 只属于 ACTIVE（其余状态一律清空，暂停/停止/收齐即不再提醒）
    CHECK (next_reminder_at IS NULL OR status = 'ACTIVE'),
    CHECK (initial_sent_at IS NULL OR tracking_due_at IS NOT NULL)
);

CREATE INDEX idx_wecom_states_reminder_due
    ON app.fulfillment_export_wecom_states (status, next_reminder_at, export_id)
    WHERE status = 'ACTIVE';

-- ③ 每次 delivery 尝试的证据（唯一键 = 数据库级「同一 initial/同一 reminder 不重复入队」）
CREATE TABLE app.fulfillment_export_wecom_deliveries (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id            BIGINT NOT NULL
                         REFERENCES app.fulfillment_export_wecom_states(export_id) ON DELETE RESTRICT,
    kind                 VARCHAR(16) NOT NULL CHECK (kind IN ('INITIAL', 'REMINDER')),
    sequence             INTEGER NOT NULL CHECK (sequence > 0),
    status               VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'FAILED', 'UNKNOWN')),
    attempts             INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts         INTEGER NOT NULL DEFAULT 2 CHECK (max_attempts >= 1),
    stage                VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED'
                         CHECK (stage IN ('SCHEDULED', 'RESOLVE_CHAT', 'UPLOAD', 'SEND', 'FINALIZED')),
    chat_id              VARCHAR(128),
    request_id           VARCHAR(128),
    ack_sent_at          TIMESTAMPTZ,
    media_id_sha256      CHAR(64),
    error_code           VARCHAR(64),
    error_message        VARCHAR(512),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (export_id, kind, sequence),
    CHECK (media_id_sha256 IS NULL OR media_id_sha256 ~ '^[0-9a-f]{64}$'),
    -- SENT 必须携带服务端 ack 接收时刻（计时起点证据），其余状态不得携带
    CHECK ((status = 'SENT') = (ack_sent_at IS NOT NULL))
);

-- ④ 历史第三方导出安全默认：LEGACY（不自动入队、不提醒、不补发）
INSERT INTO app.fulfillment_export_wecom_states
    (export_id, provider_id, status, tracking_sla_minutes, reminder_interval_minutes)
SELECT fe.id, fe.fulfillment_provider_id, 'LEGACY',
       fp.tracking_sla_minutes, fp.tracking_sla_minutes
FROM app.fulfillment_exports fe
JOIN app.fulfillment_providers fp ON fp.id = fe.fulfillment_provider_id
WHERE fe.export_kind = 'THIRD_PARTY'
ON CONFLICT (export_id) DO NOTHING;
