-- Issue #89：内部运营人员登记（姓名、企微 userid、所属责任团队）。
--
-- 系统第一次有「人」的概念：可登记内部运营人员并绑定企微 userid，从而知道
-- 「这条复核该推给谁」；responsible_team 由此可解析到具体人员列表。
--
-- 边界（与 Issue 一致）：
--  - 只做「运营人员 ↔ 企微 userid ↔ 责任团队」映射与责任归属，不做登录/角色/权限；
--  - 不把 channel_identities 当内部员工表（渠道侧身份是客户与群的证据，不是员工档案）；
--  - 不做物理删除：停用（active=false）即可，解析 seam 只返回 active 人员。
--
-- 约束语义：
--  - display_name / responsible_team 非空；responsible_team 由写入侧统一
--    trim + 大写归一（ORDER_OPS / CUSTOMER_OPS / SKU_OPS 等既有取值），DB 侧兜底
--    拒绝纯空白与未大写团队；
--  - wecom_userid 可空（未绑定）：非空时全局唯一——同一企微 userid 永远只映射一个
--    人员（停用后重新启用同一行，或先清除旧绑定再换绑）；
--  - 企微 userid 按官方规则校验：1..64 字节，首字符必须为数字或字母，可含 _ - @ .
--    四种字符；真实企微实测确认前以本保守规则为准（见 docs/agents/operator-wecom-userid.md）。
CREATE TABLE app.internal_operators (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name     VARCHAR(64) NOT NULL CHECK (btrim(display_name) <> ''),
    responsible_team VARCHAR(32) NOT NULL
                     CHECK (btrim(responsible_team) <> ''
                            AND responsible_team = upper(responsible_team)),
    wecom_userid     VARCHAR(64),
    active           BOOLEAN NOT NULL DEFAULT TRUE,
    lock_version     BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (wecom_userid IS NULL
           OR wecom_userid ~ '^[A-Za-z0-9][A-Za-z0-9_@.\-]{0,63}$')
);

-- 同一企微 userid 全局唯一；未绑定（NULL）行不互相冲突。
CREATE UNIQUE INDEX uq_internal_operators_wecom_userid
    ON app.internal_operators (wecom_userid) WHERE wecom_userid IS NOT NULL;

-- 解析 seam 按责任团队 + 启用状态查询的支撑索引。
CREATE INDEX idx_internal_operators_team_active
    ON app.internal_operators (responsible_team, active);
