-- Issue #90: durable five-minute WeCom digests for review cases and key business events.
-- Capture happens in the same database transaction as the source fact. Delivery is fenced in
-- separate durable batches so a process crash after submission becomes UNKNOWN, never a blind resend.

CREATE TABLE app.wecom_notification_batches (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsible_team    VARCHAR(128) NOT NULL CHECK (btrim(responsible_team) <> ''),
    window_start        TIMESTAMPTZ NOT NULL,
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'RUNNING', 'SENT', 'PARTIAL',
                                          'BLOCKED', 'UNKNOWN', 'FAILED')),
    next_attempt_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until         TIMESTAMPTZ,
    lease_owner         VARCHAR(128),
    last_reason_code    VARCHAR(128),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'RUNNING' AND lease_until IS NOT NULL AND lease_owner IS NOT NULL)
        OR (status <> 'RUNNING' AND lease_until IS NULL AND lease_owner IS NULL)
    )
);

CREATE INDEX idx_wecom_notification_batches_due
    ON app.wecom_notification_batches (status, next_attempt_at, id)
    WHERE status IN ('PENDING', 'RUNNING');

CREATE TABLE app.wecom_notification_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type         VARCHAR(32) NOT NULL
                        CHECK (source_type IN ('REVIEW_CASE', 'ORDER_EVENT')),
    source_id           BIGINT NOT NULL CHECK (source_id > 0),
    notification_kind   VARCHAR(32) NOT NULL
                        CHECK (notification_kind IN ('REVIEW_CASE', 'ORDER_CREATED', 'SHIPMENT_COMPLETED')),
    responsible_team    VARCHAR(128) NOT NULL CHECK (btrim(responsible_team) <> ''),
    summary             JSONB NOT NULL CHECK (jsonb_typeof(summary) = 'object'),
    window_start        TIMESTAMPTZ NOT NULL,
    available_at        TIMESTAMPTZ NOT NULL,
    batch_id            BIGINT REFERENCES app.wecom_notification_batches(id) ON DELETE RESTRICT,
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'BATCHED', 'SENT', 'PARTIAL',
                                          'BLOCKED', 'UNKNOWN', 'FAILED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_type, source_id, notification_kind),
    CHECK (
        (status = 'PENDING' AND batch_id IS NULL)
        OR (status <> 'PENDING' AND batch_id IS NOT NULL)
    )
);

CREATE INDEX idx_wecom_notification_items_due
    ON app.wecom_notification_items (available_at, responsible_team, window_start, id)
    WHERE status = 'PENDING' AND batch_id IS NULL;

CREATE INDEX idx_wecom_notification_items_batch
    ON app.wecom_notification_items (batch_id, id)
    WHERE batch_id IS NOT NULL;

CREATE TABLE app.wecom_notification_deliveries (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                BIGINT NOT NULL REFERENCES app.wecom_notification_batches(id) ON DELETE RESTRICT,
    recipient_key           VARCHAR(255) NOT NULL CHECK (btrim(recipient_key) <> ''),
    recipient_display_name  VARCHAR(64),
    recipient_userid        VARCHAR(64),
    status                  VARCHAR(16) NOT NULL
                            CHECK (status IN ('SENDING', 'SENT', 'RETRY_PENDING',
                                              'BLOCKED', 'UNKNOWN', 'FAILED')),
    attempt_count           INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    content_sha256          CHAR(64),
    request_id              VARCHAR(128),
    reason_code             VARCHAR(128),
    reason_message          VARCHAR(255),
    acknowledged_at         TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, recipient_key),
    CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
    CHECK (
        (status = 'SENT' AND request_id IS NOT NULL AND acknowledged_at IS NOT NULL)
        OR status <> 'SENT'
    )
);

CREATE INDEX idx_wecom_notification_deliveries_source
    ON app.wecom_notification_deliveries (batch_id, status, id);

-- Durable operations projection for every blocked, failed or unknown source x recipient result.
-- It is intentionally independent from operational_alerts: some notifications point only to an
-- import/message/draft subject, while operational_alerts requires an order-side foreign key.
CREATE TABLE app.wecom_notification_alerts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_key           VARCHAR(128) NOT NULL UNIQUE CHECK (btrim(alert_key) <> ''),
    delivery_id         BIGINT NOT NULL REFERENCES app.wecom_notification_deliveries(id) ON DELETE RESTRICT,
    item_id             BIGINT NOT NULL REFERENCES app.wecom_notification_items(id) ON DELETE RESTRICT,
    batch_id            BIGINT NOT NULL REFERENCES app.wecom_notification_batches(id) ON DELETE RESTRICT,
    delivery_status     VARCHAR(16) NOT NULL CHECK (delivery_status IN ('BLOCKED', 'UNKNOWN', 'FAILED')),
    severity            VARCHAR(16) NOT NULL CHECK (severity IN ('YELLOW', 'RED')),
    reason_code         VARCHAR(128),
    reason_message      VARCHAR(255),
    order_id            BIGINT REFERENCES app.orders(id) ON DELETE RESTRICT,
    order_line_id       BIGINT REFERENCES app.order_lines(id) ON DELETE RESTRICT,
    fulfillment_id      BIGINT REFERENCES app.fulfillments(id) ON DELETE RESTRICT,
    shipment_id         BIGINT REFERENCES app.shipments(id) ON DELETE RESTRICT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (delivery_id, item_id)
);

CREATE INDEX idx_wecom_notification_alerts_queue
    ON app.wecom_notification_alerts (severity, created_at DESC, id DESC);
CREATE INDEX idx_wecom_notification_alerts_batch
    ON app.wecom_notification_alerts (batch_id, id);
CREATE INDEX idx_wecom_notification_alerts_order
    ON app.wecom_notification_alerts (order_id) WHERE order_id IS NOT NULL;

CREATE FUNCTION app.wecom_notification_window_start(value TIMESTAMPTZ)
RETURNS TIMESTAMPTZ
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT (
        date_trunc('hour', value AT TIME ZONE 'UTC')
        + ((extract(minute FROM value AT TIME ZONE 'UTC')::INT / 5) * INTERVAL '5 minutes')
    ) AT TIME ZONE 'UTC'
$$;

CREATE FUNCTION app.capture_review_case_wecom_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_scope VARCHAR(16);
    v_order_no VARCHAR(64);
    v_subject_order_id BIGINT;
    v_window TIMESTAMPTZ;
BEGIN
    IF NEW.status <> 'OPEN' THEN
        RETURN NEW;
    END IF;

    v_subject_order_id := NEW.order_id;
    IF v_subject_order_id IS NULL AND NEW.order_line_id IS NOT NULL THEN
        SELECT order_id INTO v_subject_order_id
        FROM app.order_lines WHERE id = NEW.order_line_id;
    END IF;
    IF v_subject_order_id IS NULL AND NEW.fulfillment_id IS NOT NULL THEN
        SELECT ol.order_id INTO v_subject_order_id
        FROM app.fulfillments f
        JOIN app.order_lines ol ON ol.id = f.order_line_id
        WHERE f.id = NEW.fulfillment_id;
    END IF;
    IF v_subject_order_id IS NULL AND NEW.shipment_id IS NOT NULL THEN
        SELECT order_id INTO v_subject_order_id
        FROM app.shipments WHERE id = NEW.shipment_id;
    END IF;
    IF v_subject_order_id IS NULL AND NEW.raw_import_row_id IS NOT NULL THEN
        SELECT COALESCE(r.order_id, ol.order_id) INTO v_subject_order_id
        FROM app.raw_import_rows r
        LEFT JOIN app.order_lines ol ON ol.id = r.order_line_id
        WHERE r.id = NEW.raw_import_row_id;
    END IF;

    IF v_subject_order_id IS NOT NULL THEN
        SELECT data_scope, order_no INTO v_scope, v_order_no
        FROM app.orders WHERE id = v_subject_order_id;
        IF v_scope IS DISTINCT FROM 'BUSINESS' THEN
            RETURN NEW;
        END IF;
    END IF;

    v_window := app.wecom_notification_window_start(NEW.created_at);
    INSERT INTO app.wecom_notification_items (
        source_type, source_id, notification_kind, responsible_team,
        summary, window_start, available_at
    ) VALUES (
        'REVIEW_CASE', NEW.id, 'REVIEW_CASE', NEW.responsible_team,
        jsonb_strip_nulls(jsonb_build_object(
            'case_no', NEW.case_no,
            'reason_code', NEW.reason_code,
            'order_no', v_order_no,
            'order_id', v_subject_order_id,
            'order_line_id', NEW.order_line_id,
            'fulfillment_id', NEW.fulfillment_id,
            'shipment_id', NEW.shipment_id,
            'import_batch_id', NEW.import_batch_id,
            'raw_import_row_id', NEW.raw_import_row_id,
            'message_submission_id', NEW.message_submission_id,
            'order_draft_id', NEW.order_draft_id,
            'provider_tracking_draft_id', NEW.provider_tracking_draft_id
        )),
        v_window,
        v_window + INTERVAL '5 minutes'
    ) ON CONFLICT (source_type, source_id, notification_kind) DO NOTHING;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_review_case_wecom_notification
AFTER INSERT ON app.review_cases
FOR EACH ROW EXECUTE FUNCTION app.capture_review_case_wecom_notification();

CREATE FUNCTION app.capture_order_event_wecom_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_kind VARCHAR(32);
    v_team VARCHAR(128);
    v_order_no VARCHAR(64);
    v_source_channel VARCHAR(32);
    v_window TIMESTAMPTZ;
BEGIN
    IF NEW.data_scope <> 'BUSINESS'
       OR NEW.event_type_code NOT IN ('ORDER_RECEIVED', 'TRACKING_RECEIVED') THEN
        RETURN NEW;
    END IF;

    IF NEW.event_type_code = 'ORDER_RECEIVED' THEN
        v_kind := 'ORDER_CREATED';
        v_team := 'ORDER_OPS';
    ELSE
        v_kind := 'SHIPMENT_COMPLETED';
        v_team := 'FULFILLMENT_OPS';
    END IF;

    SELECT order_no, source_channel INTO v_order_no, v_source_channel
    FROM app.orders WHERE id = NEW.order_id;
    v_window := app.wecom_notification_window_start(NEW.created_at);
    INSERT INTO app.wecom_notification_items (
        source_type, source_id, notification_kind, responsible_team,
        summary, window_start, available_at
    ) VALUES (
        'ORDER_EVENT', NEW.id, v_kind, v_team,
        jsonb_strip_nulls(jsonb_build_object(
            'event_type_code', NEW.event_type_code,
            'order_no', v_order_no,
            'order_id', NEW.order_id,
            'source_channel', v_source_channel,
            'shipment_id', NEW.shipment_id
        )),
        v_window,
        v_window + INTERVAL '5 minutes'
    ) ON CONFLICT (source_type, source_id, notification_kind) DO NOTHING;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_order_event_wecom_notification
AFTER INSERT ON app.order_events
FOR EACH ROW EXECUTE FUNCTION app.capture_order_event_wecom_notification();
