-- Issues #87/#88: persisted order-draft cards, traceable click outcomes and 5s update state.

ALTER TABLE app.order_drafts
    ADD COLUMN settlement_time TIMESTAMPTZ;

-- Confirmed legacy drafts did not persist this fact on the draft, but their canonical order does.
UPDATE app.order_drafts d
SET settlement_time = o.settlement_time
FROM app.review_cases rc
JOIN app.orders o ON o.id = CASE
    WHEN rc.resolution->>'order_id' ~ '^[1-9][0-9]*$'
    THEN (rc.resolution->>'order_id')::BIGINT
END
WHERE rc.order_draft_id = d.id
  AND rc.status = 'RESOLVED'
  AND rc.resolution->>'resolution_type' = 'ORDER_DRAFT_CONFIRMED'
  AND d.status = 'CONFIRMED'
  AND d.settlement_time IS NULL;

-- Only open legacy drafts need a new missing-field gate. Closed historical drafts must not be
-- rewritten to look incomplete.
UPDATE app.order_drafts
SET missing_fields = missing_fields || '["settlement_time"]'::jsonb
WHERE status = 'OPEN'
  AND settlement_time IS NULL
  AND NOT (missing_fields ? 'settlement_time');

ALTER TABLE app.wecom_events
    ADD COLUMN event_key VARCHAR(64),
    ADD COLUMN task_id VARCHAR(128),
    ADD COLUMN order_draft_id BIGINT REFERENCES app.order_drafts(id) ON DELETE RESTRICT,
    ADD COLUMN processing_status VARCHAR(32),
    ADD COLUMN business_code VARCHAR(128),
    ADD COLUMN processed_by VARCHAR(255),
    ADD COLUMN processing_started_at TIMESTAMPTZ,
    ADD COLUMN processed_at TIMESTAMPTZ,
    ADD COLUMN processing_claim_token UUID,
    ADD COLUMN processing_attempt INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN update_status VARCHAR(32),
    ADD COLUMN update_latency_ms INTEGER,
    ADD COLUMN update_error_code VARCHAR(128),
    ADD COLUMN fallback_status VARCHAR(32),
    ADD COLUMN fallback_error_code VARCHAR(128);

ALTER TABLE app.wecom_events
    ADD CONSTRAINT wecom_events_processing_status_check CHECK (
        processing_status IS NULL OR processing_status IN (
            'RECEIVED', 'PROCESSING', 'CONFIRMED', 'MISSING_INFORMATION', 'ALREADY_CONFIRMED',
            'REJECTED', 'FAILED'
        )
    ),
    ADD CONSTRAINT wecom_events_update_status_check CHECK (
        update_status IS NULL OR update_status IN (
            'NOT_ATTEMPTED', 'SENT', 'TIMED_OUT', 'FAILED'
        )
    ),
    ADD CONSTRAINT wecom_events_fallback_status_check CHECK (
        fallback_status IS NULL OR fallback_status IN ('NOT_ATTEMPTED', 'SENT', 'FAILED')
    ),
    ADD CONSTRAINT wecom_events_update_latency_check CHECK (
        update_latency_ms IS NULL OR update_latency_ms >= 0
    ),
    ADD CONSTRAINT wecom_events_processing_claim_check CHECK (
        processing_status IS NULL
        OR (processing_status = 'RECEIVED'
            AND processing_claim_token IS NULL AND processing_attempt = 0)
        OR (processing_status <> 'RECEIVED'
            AND processing_claim_token IS NOT NULL AND processing_attempt >= 1)
    );

CREATE OR REPLACE FUNCTION app.guard_wecom_card_event_first_facts()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.event_type = 'template_card_event' AND (
        NEW.event_type IS DISTINCT FROM OLD.event_type
        OR NEW.msgid IS DISTINCT FROM OLD.msgid
        OR NEW.aibot_id IS DISTINCT FROM OLD.aibot_id
        OR NEW.chat_id IS DISTINCT FROM OLD.chat_id
        OR NEW.chat_type IS DISTINCT FROM OLD.chat_type
        OR NEW.from_user_id IS DISTINCT FROM OLD.from_user_id
        OR NEW.create_time IS DISTINCT FROM OLD.create_time
        OR NEW.raw_payload IS DISTINCT FROM OLD.raw_payload
        OR NEW.event_key IS DISTINCT FROM OLD.event_key
        OR NEW.task_id IS DISTINCT FROM OLD.task_id
        OR NEW.order_draft_id IS DISTINCT FROM OLD.order_draft_id
    ) THEN
        RAISE EXCEPTION 'template-card first facts are immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_wecom_card_event_first_facts
    BEFORE UPDATE ON app.wecom_events
    FOR EACH ROW
    EXECUTE FUNCTION app.guard_wecom_card_event_first_facts();

CREATE INDEX idx_wecom_events_task
    ON app.wecom_events (task_id, received_at DESC)
    WHERE task_id IS NOT NULL;

CREATE TABLE app.wecom_order_draft_cards (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_draft_id      BIGINT NOT NULL UNIQUE REFERENCES app.order_drafts(id) ON DELETE RESTRICT,
    draft_revision      BIGINT NOT NULL CHECK (draft_revision >= 0),
    task_id             VARCHAR(128) NOT NULL UNIQUE CHECK (btrim(task_id) <> ''),
    chat_id             VARCHAR(255) NOT NULL CHECK (btrim(chat_id) <> ''),
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'UNKNOWN', 'FAILED')),
    attempt_count       INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    request_id          VARCHAR(128),
    last_error          VARCHAR(128),
    acknowledged_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'SENT' AND request_id IS NOT NULL AND acknowledged_at IS NOT NULL)
        OR status <> 'SENT'
    )
);

CREATE INDEX idx_wecom_order_draft_cards_status
    ON app.wecom_order_draft_cards (status, id);
