-- 通用业务卡投递（#87/#88 后续）：复核事项 / 运营告警 / 整批确认播报 / 京东出库失败
-- 四类卡共用一张投递表，按 (card_domain, entity_id, entity_version) 定位。
--
-- 与 V52 的 wecom_order_draft_cards 并存而不合并：订单草稿卡有自己的 revision 门禁与
-- 确认闭环（wecom_events.order_draft_id 外键、5 秒更新状态机），强行合表会把两套
-- 生命周期搅在一起。本表只承载「渲染→发送→留痕」，不承载确认语义。
--
-- 刻意不存卡片正文：正文含客户名等业务文本，落库等于把 PII 面扩大到第二张表。
-- 发送时由 domain 对应的 WecomBusinessCardSource 按当前事实重新渲染——
-- 顺带保证发出去的一定是最新事实，而不是入队那一刻的快照。

CREATE TABLE app.wecom_business_cards (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_domain         VARCHAR(32) NOT NULL CHECK (card_domain ~ '^[a-z][a-z-]{0,31}$'),
    entity_id           BIGINT NOT NULL CHECK (entity_id >= 0),
    entity_version      BIGINT NOT NULL CHECK (entity_version >= 0),
    -- task_id 即 {domain}:{id}:v{version}，唯一约束顺带保证同一版本不会重复建卡
    task_id             VARCHAR(128) NOT NULL UNIQUE CHECK (btrim(task_id) <> ''),
    route_type          VARCHAR(16) NOT NULL CHECK (route_type IN ('SINGLE', 'GROUP')),
    chat_id             VARCHAR(255) NOT NULL CHECK (btrim(chat_id) <> ''),
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'UNKNOWN', 'FAILED', 'SUPERSEDED')),
    attempt_count       INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    request_id          VARCHAR(128),
    last_error          VARCHAR(128),
    acknowledged_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- SENT 必须同时具备平台 request_id 与 ack 时间：三者缺一就不是「用户已收到」，
    -- 而是「我们以为发出去了」——这个区分是 #81 建立的纪律，不能在这里丢掉
    CHECK (
        (status = 'SENT' AND request_id IS NOT NULL AND acknowledged_at IS NOT NULL)
        OR status <> 'SENT'
    )
);

-- worker 认领：按状态 + id 顺序取
CREATE INDEX idx_wecom_business_cards_status
    ON app.wecom_business_cards (status, id);

-- 从业务实体回溯它发过哪些卡（排障与「这事通知过谁」都要用）
CREATE INDEX idx_wecom_business_cards_entity
    ON app.wecom_business_cards (card_domain, entity_id, entity_version);
