-- 异步来源订单附件接入：先保存原件和任务，再解析/提取，避免未知模板在证据留存前丢失。
CREATE TABLE app.source_order_intake_jobs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_no                  VARCHAR(64) NOT NULL UNIQUE CHECK (btrim(job_no) <> ''),
    source_channel          VARCHAR(32) NOT NULL
                            CHECK (source_channel IN (
                                'CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI',
                                'DAZHE', 'WANGQI', 'WANQI', 'WECOM')),
    import_mode             VARCHAR(16) NOT NULL CHECK (import_mode IN ('NEW', 'REVISION')),
    parent_import_batch_id  BIGINT REFERENCES app.import_batches(id) ON DELETE RESTRICT,
    original_file_name      VARCHAR(255) NOT NULL CHECK (btrim(original_file_name) <> ''),
    content_type            VARCHAR(128),
    file_format             VARCHAR(8) NOT NULL CHECK (file_format IN ('XLSX', 'XLS', 'CSV')),
    content_sha256          CHAR(64) NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    file_ref                TEXT NOT NULL CHECK (btrim(file_ref) <> ''),
    status                  VARCHAR(32) NOT NULL DEFAULT 'RECEIVED'
                            CHECK (status IN (
                                'RECEIVED', 'PROCESSING', 'NEEDS_EXTRACTION', 'NEEDS_REVIEW',
                                'READY', 'IMPORTING', 'OUTBOUND_SUBMITTING', 'SUCCEEDED',
                                'FAILED', 'RECONCILIATION_REQUIRED', 'COMPLETED')),
    error_code              VARCHAR(64),
    error_detail            JSONB,
    import_batch_id         BIGINT REFERENCES app.import_batches(id) ON DELETE RESTRICT,
    idempotency_key         VARCHAR(255) NOT NULL CHECK (btrim(idempotency_key) <> ''),
    submitted_by            VARCHAR(128) NOT NULL CHECK (btrim(submitted_by) <> ''),
    lock_version            BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (import_mode = 'NEW' AND parent_import_batch_id IS NULL)
        OR (import_mode = 'REVISION' AND parent_import_batch_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_source_order_intake_content
    ON app.source_order_intake_jobs (
        source_channel,
        content_sha256,
        import_mode,
        COALESCE(parent_import_batch_id, 0));

CREATE INDEX idx_source_order_intake_status
    ON app.source_order_intake_jobs (status, id);

CREATE TRIGGER trg_source_order_intake_jobs_updated_at
BEFORE UPDATE ON app.source_order_intake_jobs
FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();

