-- Business Follow-up intake and explicit +1 organization dispatch (Issue #146).
-- Raw material remains in the existing channel message/media evidence chain; this table
-- stores only the stable submission reference and the employee's authorized draft.

CREATE SEQUENCE app.business_followup_no_seq;

CREATE TABLE app.business_followups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    followup_no VARCHAR(32) NOT NULL DEFAULT
        ('BF-' || lpad(nextval('app.business_followup_no_seq')::text, 10, '0')),
    message_submission_id BIGINT NOT NULL,
    employee_draft TEXT NOT NULL CHECK (btrim(employee_draft) <> ''),
    source_revision INTEGER NOT NULL DEFAULT 1 CHECK (source_revision > 0),
    stage VARCHAR(32) NOT NULL DEFAULT 'PENDING_ORGANIZATION'
        CHECK (stage IN ('PENDING_ORGANIZATION', 'ORGANIZING', 'DRAFT_READY')),
    processing_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED'
        CHECK (processing_status IN ('NOT_STARTED', 'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    created_by VARCHAR(128) NOT NULL CHECK (btrim(created_by) <> ''),
    designated_reviewer VARCHAR(128),
    agent_slug VARCHAR(64),
    agent_version INTEGER,
    organization_task_key VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_business_followups_no UNIQUE (followup_no),
    CONSTRAINT uq_business_followups_submission UNIQUE (message_submission_id),
    CONSTRAINT uq_business_followups_task_key UNIQUE (organization_task_key),
    CONSTRAINT ck_business_followups_agent_pair CHECK (
        (agent_slug IS NULL AND agent_version IS NULL)
        OR (agent_slug IS NOT NULL AND agent_version IS NOT NULL AND agent_version > 0)
    ),
    CONSTRAINT fk_business_followups_submission FOREIGN KEY (message_submission_id)
        REFERENCES app.message_submissions(id),
    CONSTRAINT fk_business_followups_agent FOREIGN KEY (agent_slug, agent_version)
        REFERENCES app.agent_definitions(agent_slug, version)
);

CREATE INDEX idx_business_followups_stage
    ON app.business_followups(stage, processing_status, updated_at DESC);
