-- Issue #130: fail-closed Kehuzx read evidence and versioned customer follow-up drafts.

CREATE TABLE app.kehuzx_read_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id VARCHAR(64) NOT NULL CHECK (btrim(agent_run_id) <> ''),
    tool_name VARCHAR(64) NOT NULL CHECK (tool_name IN (
        'search_customers', 'get_customer_detail', 'search_demands',
        'search_orders', 'get_order_detail'
    )),
    arguments_digest CHAR(64) NOT NULL CHECK (arguments_digest ~ '^[0-9a-f]{64}$'),
    response_digest CHAR(64) NOT NULL CHECK (response_digest ~ '^[0-9a-f]{64}$'),
    response_payload JSONB NOT NULL CHECK (jsonb_typeof(response_payload) = 'object'),
    contract_version VARCHAR(64) NOT NULL CHECK (btrim(contract_version) <> ''),
    upstream_commit VARCHAR(64),
    queried_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kehuzx_read_evidence_run
    ON app.kehuzx_read_evidence(agent_run_id, id);

CREATE TABLE app.kehuzx_read_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id VARCHAR(64) NOT NULL CHECK (btrim(agent_run_id) <> ''),
    tool_name VARCHAR(64) NOT NULL CHECK (tool_name IN (
        'search_customers', 'get_customer_detail', 'search_demands',
        'search_orders', 'get_order_detail'
    )),
    failure_code VARCHAR(64) NOT NULL CHECK (failure_code IN (
        'KEHUZX_NOT_CONFIGURED', 'KEHUZX_UNREACHABLE', 'KEHUZX_TIMEOUT',
        'KEHUZX_AUTH_REJECTED', 'KEHUZX_CONTRACT_DRIFT', 'KEHUZX_TOOL_FAILED'
    )),
    contract_version VARCHAR(64) NOT NULL CHECK (btrim(contract_version) <> ''),
    upstream_commit VARCHAR(64),
    queried_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kehuzx_read_failures_run
    ON app.kehuzx_read_failures(agent_run_id, id);

ALTER TABLE app.business_followups
    DROP CONSTRAINT business_followups_stage_check,
    ADD CONSTRAINT business_followups_stage_check CHECK (
        stage IN ('PENDING_ORGANIZATION', 'ORGANIZING', 'DRAFT_READY', 'NEEDS_INPUT')
    ),
    ADD COLUMN current_draft_version INTEGER
        CHECK (current_draft_version IS NULL OR current_draft_version > 0);

CREATE TABLE app.business_followup_draft_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    followup_id BIGINT NOT NULL REFERENCES app.business_followups(id) ON DELETE RESTRICT,
    version INTEGER NOT NULL CHECK (version > 0),
    source_revision INTEGER NOT NULL CHECK (source_revision > 0),
    status VARCHAR(24) NOT NULL CHECK (status IN ('DRAFT', 'NEEDS_INPUT')),
    agent_run_id VARCHAR(64) NOT NULL CHECK (btrim(agent_run_id) <> ''),
    agent_slug VARCHAR(64) NOT NULL,
    agent_version INTEGER NOT NULL CHECK (agent_version > 0),
    content JSONB NOT NULL CHECK (jsonb_typeof(content) = 'object'),
    zimu_source_summary JSONB NOT NULL CHECK (jsonb_typeof(zimu_source_summary) = 'object'),
    kehuzx_source_summary JSONB NOT NULL CHECK (jsonb_typeof(kehuzx_source_summary) = 'object'),
    upstream_refs JSONB NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(upstream_refs) = 'array'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_business_followup_draft_version UNIQUE (followup_id, version),
    CONSTRAINT fk_business_followup_draft_agent FOREIGN KEY (agent_slug, agent_version)
        REFERENCES app.agent_definitions(agent_slug, version)
);

CREATE INDEX idx_business_followup_drafts_current
    ON app.business_followup_draft_versions(followup_id, version DESC);

INSERT INTO app.agent_definitions (
    agent_slug, name, description, system_prompt, prompt_version, model_ref,
    enabled, version, status, activated_by, activated_at, allow_write,
    guard_exemptions, output_schema, tool_whitelist)
VALUES (
    'customer-followup-agent',
    '客户跟进整理 Agent',
    '依据子牧来源材料与 Kehuzx 只读事实生成可核对草稿；不创建或修改任何 Kehuzx 数据。',
    $$你是客户跟进整理 Agent。输入只包含子牧来源编号和服务端从员工草稿中提取的 Kehuzx 客户编号 customer_identifiers；员工自由文本、个人信息和订单编号不会进入模型。你只能通过五个 kehuzx_ 前缀的只读工具核对客户、需求和订单事实，绝不调用或建议调用写工具。

硬性规则：
1. customer_identifiers 必须恰好包含一个 KH-YYMMDD-NNN 客户编号；为空或多个时直接 requires_human=true 并要求补充唯一客户编号。恰好一个时调用一次 kehuzx_search_customers；服务端会忽略模型参数并绑定该编号。恰好一个候选才可继续，严禁猜客户身份。
2. 只有客户唯一后才可用 customer_id 调 kehuzx_get_customer_detail / kehuzx_search_demands；只有订单编号或名称明确时才可查订单。
3. 子牧输入是 ZIMU 来源；远端工具结果是 KEHUZX 来源。输出 facts 的每项必须标 source，不得把员工陈述写成 Kehuzx 已确认事实。
4. 工具超时、不可达、鉴权失败、契约漂移或返回错误时 requires_human=true，不得用常识补全。
5. 不输出手机号、地址、凭据或原始错误；客户和订单只输出可核对的业务编号/ID与名称。
6. 输出必须严格符合 output_schema。$$,
    'customer-followup-v1',
    'app.agent',
    true, 1, 'active', 'system', CURRENT_TIMESTAMP, false,
    '["PII"]'::jsonb,
    $${
      "type": "object",
      "additionalProperties": false,
      "required": ["title", "summary", "facts", "requires_human", "missing_fields"],
      "properties": {
        "title": {"type": "string"},
        "summary": {"type": "string"},
        "facts": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["source", "label", "value"],
            "properties": {
              "source": {"type": "string", "enum": ["ZIMU", "KEHUZX"]},
              "label": {"type": "string"},
              "value": {"type": "string"}
            }
          }
        },
        "requires_human": {"type": "boolean"},
        "missing_fields": {"type": "array", "items": {"type": "string"}}
      }
    }$$::jsonb,
    '["kehuzx_search_customers","kehuzx_get_customer_detail","kehuzx_search_demands","kehuzx_search_orders","kehuzx_get_order_detail"]'::jsonb
);
