-- Issue #148: confirmed Business Follow-up drafts project durable, independently executed Assignments.

ALTER TABLE app.business_followup_approvals
    ADD CONSTRAINT uq_business_followup_approval_trace
        UNIQUE (id, followup_id, draft_version);

CREATE TABLE app.business_followup_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    followup_id BIGINT NOT NULL,
    draft_version INTEGER NOT NULL CHECK (draft_version > 0),
    approval_id BIGINT NOT NULL,
    agent_run_id VARCHAR(64) NOT NULL CHECK (btrim(agent_run_id) <> ''),
    task_type VARCHAR(64) NOT NULL CHECK (task_type IN ('KEHUZX_CUSTOMER_LINK')),
    logical_target VARCHAR(255) NOT NULL CHECK (btrim(logical_target) <> ''),
    assignee_type VARCHAR(24) NOT NULL CHECK (assignee_type IN (
        'INTERNAL_OPERATOR', 'TEAM', 'DETERMINISTIC_MCP', 'SPECIALIST_AGENT'
    )),
    assignee_ref VARCHAR(128) NOT NULL CHECK (btrim(assignee_ref) <> ''),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' CHECK (status IN (
        'PENDING', 'RUNNING', 'WAITING_HUMAN', 'SUCCEEDED', 'FAILED',
        'RECONCILIATION_REQUIRED'
    )),
    due_at TIMESTAMPTZ NOT NULL,
    priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL'
        CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    idempotency_key VARCHAR(255) NOT NULL CHECK (btrim(idempotency_key) <> ''),
    execution_task_key VARCHAR(255) NOT NULL CHECK (btrim(execution_task_key) <> ''),
    request_id VARCHAR(128) CHECK (request_id IS NULL OR btrim(request_id) <> ''),
    external_entity_type VARCHAR(64),
    external_entity_id VARCHAR(128),
    result_code VARCHAR(64) CHECK (
        result_code IS NULL OR result_code ~ '^[A-Z][A-Z0-9_]{2,63}$'
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_business_followup_assignment_draft
        FOREIGN KEY (followup_id, draft_version)
        REFERENCES app.business_followup_draft_versions(followup_id, version)
        ON DELETE RESTRICT,
    CONSTRAINT fk_business_followup_assignment_approval
        FOREIGN KEY (approval_id, followup_id, draft_version)
        REFERENCES app.business_followup_approvals(id, followup_id, draft_version)
        ON DELETE RESTRICT,
    CONSTRAINT uq_business_followup_assignment_target
        UNIQUE (followup_id, draft_version, task_type, logical_target),
    CONSTRAINT uq_business_followup_assignment_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_business_followup_assignment_execution_task UNIQUE (execution_task_key),
    CONSTRAINT business_followup_assignment_external_entity_pair CHECK (
        (external_entity_type IS NULL AND external_entity_id IS NULL)
        OR (external_entity_type IS NOT NULL AND btrim(external_entity_type) <> ''
            AND external_entity_id IS NOT NULL AND btrim(external_entity_id) <> '')
    ),
    CONSTRAINT business_followup_assignment_outcome_check CHECK (
        (status = 'PENDING' AND started_at IS NULL AND completed_at IS NULL
            AND result_code IS NULL AND external_entity_type IS NULL)
        OR (status = 'RUNNING' AND started_at IS NOT NULL AND completed_at IS NULL
            AND result_code IS NULL AND request_id IS NOT NULL)
        OR (status = 'WAITING_HUMAN' AND started_at IS NOT NULL AND completed_at IS NULL
            AND result_code IS NOT NULL)
        OR (status IN ('SUCCEEDED', 'RECONCILIATION_REQUIRED')
            AND started_at IS NOT NULL AND completed_at IS NOT NULL
            AND result_code IS NOT NULL AND request_id IS NOT NULL)
        OR (status = 'FAILED'
            AND started_at IS NOT NULL AND completed_at IS NOT NULL
            AND result_code IS NOT NULL)
    ),
    CONSTRAINT business_followup_assignment_success_result_check CHECK (
        status <> 'SUCCEEDED'
        OR (result_code = 'KEHUZX_CUSTOMER_LINKED'
            AND external_entity_type = 'KEHUZX_CUSTOMER'
            AND external_entity_id IS NOT NULL)
    )
);

CREATE INDEX idx_business_followup_assignments_followup
    ON app.business_followup_assignments(followup_id, draft_version, id);

CREATE INDEX idx_business_followup_assignments_due
    ON app.business_followup_assignments(status, due_at, id)
    WHERE status IN ('PENDING', 'RUNNING', 'WAITING_HUMAN', 'RECONCILIATION_REQUIRED');

-- Upgrade-safe backfill: confirmations applied before V61 still receive exactly one projection task.
INSERT INTO app.async_tasks (task_type, payload_ref, idempotency_key, max_attempts)
SELECT 'BUSINESS_FOLLOWUP_ASSIGNMENT_PROJECT',
       'followup-assignment-projection:' || a.id,
       'followup-assignment-projection:' || a.id,
       3
FROM app.business_followup_approvals a
JOIN app.business_followups bf ON bf.id=a.followup_id
JOIN app.business_followup_draft_versions d
  ON d.followup_id=a.followup_id AND d.version=a.draft_version
WHERE a.decision='CONFIRM' AND a.application_status='APPLIED'
  AND a.draft_version=bf.current_confirmed_draft_version
  AND d.status='CONFIRMED'
ON CONFLICT (idempotency_key) DO NOTHING;
