-- 商品档案·成本表全列留存：把「A产品成本核算26.3.29.xlsx / 成品 sheet」逐行原样收进库，
-- 一行成本表 = 本表一行，表格正身 A..AU 共 47 列全部记下，且**保持原表列序**。
--
-- 为什么 fields 是 jsonb **数组**而不是对象：PostgreSQL 的 jsonb 对象不保证键序（按键长
-- 与字节序重排），用对象存「列头→值」会把原表列序洗掉。数组的元素顺序 jsonb 会原样保留，
-- 所以 fields 的数组下标就是原表列序：fields[1] = A 列，fields[47] = AU 列。
-- 元素形如 {"column":"AI","name":"线下供货成本/份","value":"8.8761888888889"}。
-- 空单元格保留元素、value 记 null（不跳过），这样同一列在每行的数组下标恒定。
-- AK 列在表头行是空的，但列列有数据，属于表格正身，按「（AK 列无表头）」留名收进来。
--
-- 列语义（2026-08-27 用户拍板，钉死在此以免后人再猜）：
--   AI「线下供货成本/份」= 成本（权威成本列）；
--   AJ「售价」          = 不含运费的售价。
-- 本表只做档案留存：**不**回写 app.skus.purchase_price / retail_price。成本表按「份」
-- （500g 单袋）计价，库内 SKU 多数按京东在售规格「500g*2」计价，单位口径与治理路线
-- （authoritative-jd-sku-catalog.json 重生成 vs 裸写）都还没拍板；六个成本列与售价既然
-- 已原值在此，读的人自己按需换算，不由本表替业务预选口径。
--
-- extra_cells：AU 之后（AV..BF）是表格右侧零散的手工草稿格（第 8 行、第 56-60 行），
-- 没有表头、也不是表的列，不混进 fields 冒充档案字段；但也不丢，另存于此。
--
-- matched_sku_id / matched_product_id 可空：档案先落，挂接后补。品名匹配达不到零猜测门槛的
-- 行（详见 docs/research/jd-code-cost-mapping-2026-08-27.md §4）一律留空，等人工挂接。
CREATE TABLE app.product_archive_sheets (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_name   VARCHAR(255) NOT NULL CHECK (btrim(source_file_name) <> ''),
    source_file_sha256 CHAR(64) NOT NULL CHECK (source_file_sha256 ~ '^[0-9a-f]{64}$'),
    sheet_name         VARCHAR(128) NOT NULL CHECK (btrim(sheet_name) <> ''),
    row_no             INTEGER NOT NULL CHECK (row_no > 0),
    product_name       VARCHAR(255) NOT NULL CHECK (btrim(product_name) <> ''),
    fields             JSONB NOT NULL CHECK (jsonb_typeof(fields) = 'array'),
    extra_cells        JSONB NOT NULL DEFAULT '[]'::jsonb
                       CHECK (jsonb_typeof(extra_cells) = 'array'),
    matched_sku_id     BIGINT REFERENCES app.skus(id) ON DELETE RESTRICT,
    matched_product_id BIGINT REFERENCES app.products(id) ON DELETE RESTRICT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_file_sha256, row_no)
);

-- 读侧：商品档案详情按 matched_product_id 取该商品的成本表行。
CREATE INDEX idx_product_archive_sheets_product
    ON app.product_archive_sheets (matched_product_id)
    WHERE matched_product_id IS NOT NULL;

CREATE INDEX idx_product_archive_sheets_sku
    ON app.product_archive_sheets (matched_sku_id)
    WHERE matched_sku_id IS NOT NULL;

COMMENT ON TABLE app.product_archive_sheets IS
    '商品档案·成本表全列留存：一行 = 成本表一行，fields 数组序即原表列序；只存档不回写 skus 价格';
COMMENT ON COLUMN app.product_archive_sheets.fields IS
    'jsonb 数组，元素 {"column":列字母,"name":列头,"value":单元格文本}；数组序 == 原表列序（对象不保序，故必须用数组），空单元格 value 记 null 保位';
COMMENT ON COLUMN app.product_archive_sheets.extra_cells IS
    '表格正身右侧（AU 之后）零散手工草稿格，没有表头也不是表的列；不丢数据但不冒充档案字段';
COMMENT ON COLUMN app.product_archive_sheets.row_no IS
    '原表 Excel 行号（含表头行，故数据行从 2 起），与 source_file_sha256 一起构成幂等键';
COMMENT ON COLUMN app.product_archive_sheets.matched_product_id IS
    '挂接到的商品档案；只在确定无争议时填，其余留空待人工挂接';
