-- Issue #147: version-fenced Business Follow-up approval facts and WeCom callback linkage.

-- Never rewrite a correlation ID that may already exist on an externally delivered card. Legacy
-- rows remain exact-match capabilities in the outbox; all newly created rows use the opaque shape.

UPDATE app.wecom_order_draft_cards
SET task_id = 'order-draft_' || order_draft_id || '_v' || draft_revision
        || '_' || replace(gen_random_uuid()::text, '-', '')
WHERE status IN ('PENDING', 'FAILED')
  AND task_id ~ '^order-draft:[1-9][0-9]*$';

ALTER TABLE app.wecom_order_draft_cards
    DROP CONSTRAINT wecom_order_draft_cards_task_id_check,
    ADD CONSTRAINT wecom_order_draft_cards_task_id_check CHECK (
        task_id ~ '^order-draft:[1-9][0-9]*$'
        OR task_id ~ '^order-draft_[1-9][0-9]{0,18}_v[0-9]{1,19}_[0-9a-f]{32}$'
    );

UPDATE app.wecom_business_cards
SET task_id = regexp_replace(
        task_id,
        '^([a-z][a-z-]{0,31}):([0-9]{1,19}):([vg][0-9]{1,19})$',
        '\1_\2_\3') || '_' || replace(gen_random_uuid()::text, '-', '')
WHERE status IN ('PENDING', 'FAILED')
  AND task_id ~ '^([a-z][a-z-]{0,31}):([0-9]{1,19}):([vg][0-9]{1,19})$';

ALTER TABLE app.wecom_business_cards
    DROP CONSTRAINT wecom_business_cards_task_id_check,
    ADD CONSTRAINT wecom_business_cards_task_id_check CHECK (
        task_id ~ '^[a-z][a-z-]{0,31}:[0-9]{1,19}:[vg][0-9]{1,19}$'
        OR task_id ~ '^[a-z][a-z-]{0,31}_[0-9]{1,19}_[vg][0-9]{1,19}_[0-9a-f]{32}$'
        -- 2026-08-27 合流补充：企微线的规范 task_id（WecomTaskId.value()，无 hex 后缀）
        -- 已在生产运行（preship_19_v1 / preship-batch_26_v2 / export_…_g3 等），
        -- 版本断言由 id 内的 v/g 段承担，必须放行；缺这条曾把 V67 顶翻、全栈起不来。
        OR task_id ~ '^[a-z][a-z-]{0,31}_[0-9]{1,19}_[vg][0-9]{1,19}$'
    ),
    ADD CONSTRAINT uq_wecom_business_cards_entity_version
        UNIQUE (card_domain, entity_id, entity_version);

CREATE OR REPLACE FUNCTION app.reject_new_legacy_wecom_task_id()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_TABLE_NAME = 'wecom_order_draft_cards'
            AND NEW.task_id ~ '^order-draft:[1-9][0-9]*$' THEN
        RAISE EXCEPTION 'new order-draft task_id must use an opaque authorization reference'
            USING ERRCODE = '23514';
    END IF;
    IF TG_TABLE_NAME = 'wecom_business_cards'
            AND NEW.task_id ~ '^[a-z][a-z-]{0,31}:[0-9]{1,19}:[vg][0-9]{1,19}$' THEN
        RAISE EXCEPTION 'new business-card task_id must use an opaque authorization reference'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER reject_new_legacy_order_draft_task_id
BEFORE INSERT OR UPDATE OF task_id ON app.wecom_order_draft_cards
FOR EACH ROW EXECUTE FUNCTION app.reject_new_legacy_wecom_task_id();

CREATE TRIGGER reject_new_legacy_business_card_task_id
BEFORE INSERT OR UPDATE OF task_id ON app.wecom_business_cards
FOR EACH ROW EXECUTE FUNCTION app.reject_new_legacy_wecom_task_id();

-- Existing rows predate the operator mapping and therefore remain nullable. All new approval
-- commands bind the designated operator explicitly and snapshot that identity on the approval.
ALTER TABLE app.business_followups
    ADD COLUMN designated_reviewer_operator_id BIGINT
        REFERENCES app.internal_operators(id) ON DELETE RESTRICT,
    ADD COLUMN current_confirmed_draft_version INTEGER
        CHECK (current_confirmed_draft_version IS NULL OR current_confirmed_draft_version > 0);

ALTER TABLE app.business_followups
    DROP CONSTRAINT business_followups_stage_check,
    ADD CONSTRAINT business_followups_stage_check CHECK (
        stage IN (
            'PENDING_ORGANIZATION', 'ORGANIZING', 'DRAFT_READY', 'NEEDS_INPUT',
            'PENDING_APPROVAL', 'CONFIRMED', 'PAUSED'
        )
    ),
    ADD CONSTRAINT fk_business_followups_confirmed_draft
        FOREIGN KEY (id, current_confirmed_draft_version)
        REFERENCES app.business_followup_draft_versions(followup_id, version)
        ON DELETE RESTRICT;

-- DRAFT was a transient name from the organization-only slice. READY makes the business meaning
-- explicit before adding the three terminal dispositions; content and version are not rewritten.
ALTER TABLE app.business_followup_draft_versions
    DROP CONSTRAINT business_followup_draft_versions_status_check;

UPDATE app.business_followup_draft_versions
SET status = 'READY'
WHERE status = 'DRAFT';

ALTER TABLE app.business_followup_draft_versions
    ADD CONSTRAINT business_followup_draft_versions_status_check CHECK (
        status IN ('READY', 'NEEDS_INPUT', 'SUPERSEDED', 'CONFIRMED', 'PAUSED')
    );

CREATE TABLE app.business_followup_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    followup_id BIGINT NOT NULL,
    draft_version INTEGER NOT NULL CHECK (draft_version > 0),
    order_draft_id BIGINT,
    order_draft_revision BIGINT CHECK (order_draft_revision IS NULL OR order_draft_revision >= 0),
    designated_reviewer_operator_id BIGINT NOT NULL
        REFERENCES app.internal_operators(id) ON DELETE RESTRICT,
    decided_by_operator_id BIGINT NOT NULL
        REFERENCES app.internal_operators(id) ON DELETE RESTRICT,
    decision VARCHAR(24) NOT NULL CHECK (
        decision IN ('CONFIRM', 'REDO', 'NEEDS_INPUT', 'PAUSE')
    ),
    reason TEXT CHECK (
        (decision = 'CONFIRM' AND (reason IS NULL OR btrim(reason) <> ''))
        OR (decision <> 'CONFIRM' AND reason IS NOT NULL AND btrim(reason) <> '')
    ),
    source_kind VARCHAR(16) NOT NULL CHECK (source_kind IN ('WECOM_CARD', 'REST')),
    source_event_id BIGINT
        REFERENCES app.wecom_events(id) ON DELETE RESTRICT,
    request_id VARCHAR(128) NOT NULL CHECK (btrim(request_id) <> ''),
    idempotency_key VARCHAR(255) NOT NULL CHECK (btrim(idempotency_key) <> ''),
    request_fingerprint CHAR(64) NOT NULL
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    application_status VARCHAR(16) NOT NULL DEFAULT 'PENDING' CHECK (
        application_status IN ('PENDING', 'APPLIED', 'FAILED', 'SUPERSEDED')
    ),
    application_failure_code VARCHAR(64) CHECK (
        application_failure_code IS NULL
        OR application_failure_code ~ '^[A-Z][A-Z0-9_]{2,63}$'
    ),
    applied_at TIMESTAMPTZ,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_business_followup_approval_draft
        FOREIGN KEY (followup_id, draft_version)
        REFERENCES app.business_followup_draft_versions(followup_id, version)
        ON DELETE RESTRICT,
    CONSTRAINT business_followup_approval_order_draft_pair_check CHECK (
        (order_draft_id IS NULL AND order_draft_revision IS NULL)
        OR (order_draft_id IS NOT NULL AND order_draft_revision IS NOT NULL)
    ),
    CONSTRAINT uq_business_followup_approval_draft UNIQUE (followup_id, draft_version),
    CONSTRAINT uq_business_followup_approval_request UNIQUE (request_id),
    CONSTRAINT uq_business_followup_approval_idempotency UNIQUE (followup_id, idempotency_key),
    CONSTRAINT business_followup_approval_source_check CHECK (
        (source_kind = 'WECOM_CARD' AND source_event_id IS NOT NULL)
        OR (source_kind = 'REST' AND source_event_id IS NULL)
    ),
    CONSTRAINT business_followup_approval_application_outcome_check CHECK (
        (application_status = 'PENDING'
            AND application_failure_code IS NULL AND applied_at IS NULL)
        OR (application_status = 'FAILED'
            AND application_failure_code IS NOT NULL AND applied_at IS NULL)
        OR (application_status IN ('APPLIED', 'SUPERSEDED')
            AND application_failure_code IS NULL AND applied_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_business_followup_approval_event
    ON app.business_followup_approvals(source_event_id)
    WHERE source_event_id IS NOT NULL;

CREATE INDEX idx_business_followup_approvals_operator
    ON app.business_followup_approvals(decided_by_operator_id, decided_at DESC);

ALTER TABLE app.wecom_events
    ADD COLUMN business_followup_id BIGINT
        REFERENCES app.business_followups(id) ON DELETE RESTRICT,
    ADD COLUMN business_followup_draft_version INTEGER,
    ADD COLUMN business_followup_approval_id BIGINT
        REFERENCES app.business_followup_approvals(id) ON DELETE RESTRICT,
    ADD CONSTRAINT wecom_events_business_followup_draft_pair_check CHECK (
        (business_followup_id IS NULL AND business_followup_draft_version IS NULL)
        OR (business_followup_id IS NOT NULL AND business_followup_draft_version IS NOT NULL
            AND business_followup_draft_version > 0)
    ),
    ADD CONSTRAINT fk_wecom_events_business_followup_draft
        FOREIGN KEY (business_followup_id, business_followup_draft_version)
        REFERENCES app.business_followup_draft_versions(followup_id, version)
        ON DELETE RESTRICT;

ALTER TABLE app.wecom_events
    DROP CONSTRAINT wecom_events_processing_status_check,
    ADD CONSTRAINT wecom_events_processing_status_check CHECK (
        processing_status IS NULL OR processing_status IN (
            'RECEIVED', 'PROCESSING', 'ACCEPTED', 'CONFIRMED', 'MISSING_INFORMATION',
            'ALREADY_CONFIRMED', 'REJECTED', 'FAILED'
        )
    );

-- Follow-up identity and expected draft version arrive from the callback and are first facts.
-- approval_id is a processing result: it may be filled once after the Approval insert, then it is
-- immutable as well. This preserves the existing order-draft event guard in the same trigger.
CREATE OR REPLACE FUNCTION app.guard_wecom_card_event_first_facts()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.event_type IN ('template_card_event', 'business_followup_card_event') AND (
        NEW.event_type IS DISTINCT FROM OLD.event_type
        OR NEW.msgid IS DISTINCT FROM OLD.msgid
        OR NEW.aibot_id IS DISTINCT FROM OLD.aibot_id
        OR NEW.chat_id IS DISTINCT FROM OLD.chat_id
        OR NEW.chat_type IS DISTINCT FROM OLD.chat_type
        OR NEW.from_user_id IS DISTINCT FROM OLD.from_user_id
        OR NEW.create_time IS DISTINCT FROM OLD.create_time
        OR NEW.raw_payload IS DISTINCT FROM OLD.raw_payload
        OR NEW.event_key IS DISTINCT FROM OLD.event_key
        OR NEW.task_id IS DISTINCT FROM OLD.task_id
        OR NEW.order_draft_id IS DISTINCT FROM OLD.order_draft_id
        OR NEW.business_followup_id IS DISTINCT FROM OLD.business_followup_id
        OR NEW.business_followup_draft_version IS DISTINCT FROM OLD.business_followup_draft_version
        OR (OLD.business_followup_approval_id IS NOT NULL
            AND NEW.business_followup_approval_id IS DISTINCT FROM OLD.business_followup_approval_id)
    ) THEN
        RAISE EXCEPTION 'template-card first facts are immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE INDEX idx_wecom_events_business_followup
    ON app.wecom_events(business_followup_id, business_followup_draft_version, received_at DESC)
    WHERE business_followup_id IS NOT NULL;
