-- 显式数据质量证据独立于派生 readiness；只保存人工/审计事实，不保存 ready 状态。
CREATE TABLE app.sku_data_quality_flags (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id              BIGINT NOT NULL REFERENCES app.skus(id) ON DELETE RESTRICT,
    flag_code           VARCHAR(64) NOT NULL,
    blocking_reason     VARCHAR(64),
    message             VARCHAR(500) NOT NULL,
    action              VARCHAR(1000) NOT NULL,
    evidence            JSONB NOT NULL DEFAULT '{}'::JSONB CHECK (jsonb_typeof(evidence) = 'object'),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    lock_version        BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sku_id, flag_code),
    CHECK (btrim(flag_code) <> ''),
    CHECK (blocking_reason IS NULL OR blocking_reason IN ('BARCODE_CONFLICT', 'REVIEW_REQUIRED')),
    CHECK (btrim(message) <> ''),
    CHECK (btrim(action) <> '')
);

CREATE INDEX idx_sku_data_quality_flags_active
    ON app.sku_data_quality_flags(sku_id, blocking_reason, flag_code)
    WHERE active = TRUE;

CREATE TRIGGER trg_sku_data_quality_flags_updated_at
BEFORE UPDATE ON app.sku_data_quality_flags
FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();
