-- 定时平台拉取 + 自动发货的运行记录。
--
-- 存在的理由有三个，缺一个都不够：
--   1. 跨实例单飞：run_key 唯一约束让「今天的 09:00 这一次」在整个集群里只可能跑一次。
--      定时任务在多实例部署下会同时触发，没有这个约束就是三个实例同时拉三个平台。
--   2. 通知载体：企微业务卡管道要求「实体 + 版本」才能扫描发卡（见 WecomBusinessCardSource
--      #pending 的纪律）。一次运行就是那个实体，lock_version 就是那个版本。
--   3. 事后追责：自动发货是花真钱的动作。哪一次运行确认了哪些批次、跳过了哪些、
--      为什么跳过，必须留下与审计日志相互印证的第二份记录。
--
-- 刻意不存收件人任何字段：本表的摘要会被渲染进企微群卡片，PII 一旦进来就跟着进群。
CREATE TABLE app.scheduled_pull_runs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- {yyyy-MM-dd}:{slot}，例如 2026-08-28:MORNING。日期而非时间戳：
    -- 同一时段被重复触发（重启、时钟回拨、人工重放）必须命中同一行而不是新建一行。
    run_key         VARCHAR(64) NOT NULL UNIQUE CHECK (btrim(run_key) <> ''),
    slot            VARCHAR(16) NOT NULL CHECK (slot IN ('MORNING', 'EVENING', 'MANUAL')),
    run_date        DATE NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'RUNNING'
                    CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    -- 每渠道一条：{channel, status, business_code, message}。无 PII。
    pull_summary    JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(pull_summary) = 'array'),
    -- 每批次一条：{batch_id, batch_no, outcome, reason_codes, detail}。无 PII。
    ship_summary    JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(ship_summary) = 'array'),
    -- 需要人看的问题条数；为 0 时不发卡——没问题就不该打扰人。
    problem_count   INTEGER NOT NULL DEFAULT 0 CHECK (problem_count >= 0),
    shipped_batches INTEGER NOT NULL DEFAULT 0 CHECK (shipped_batches >= 0),
    lock_version    BIGINT NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    started_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 终态必须有结束时间：没有结束时间的 COMPLETED 是「我们以为跑完了」，不是跑完了。
    CHECK (status = 'RUNNING' OR finished_at IS NOT NULL)
);

-- 发卡扫描按 (status 终态, 有问题, 时间) 取，走这个索引。
CREATE INDEX idx_scheduled_pull_runs_notify
    ON app.scheduled_pull_runs (finished_at)
    WHERE status <> 'RUNNING' AND problem_count > 0;

CREATE TRIGGER trg_scheduled_pull_runs_updated_at
BEFORE UPDATE ON app.scheduled_pull_runs
FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();

COMMENT ON TABLE app.scheduled_pull_runs IS
    '定时三平台拉取与自动发货的一次运行；run_key 唯一约束兼作跨实例单飞门禁';
