-- ---------------------------------------------------------------------------
-- 企业微信消息管线：异步任务、提交、解释、媒体、草稿与渠道身份
-- 一期所有表在此一次性建立，后续票只增加 Java 层实现，不再扩展 schema 冲突面。
-- ---------------------------------------------------------------------------

CREATE TABLE app.async_tasks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type           VARCHAR(64) NOT NULL CHECK (btrim(task_type) <> ''),
    payload_ref         VARCHAR(512) NOT NULL CHECK (btrim(payload_ref) <> ''),
    status              VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    attempts            INT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts        INT NOT NULL DEFAULT 3 CHECK (max_attempts >= 1),
    next_run_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until         TIMESTAMPTZ,
    lease_owner         VARCHAR(128),
    last_error          TEXT,
    idempotency_key     VARCHAR(255) NOT NULL UNIQUE CHECK (btrim(idempotency_key) <> ''),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_async_tasks_due
    ON app.async_tasks (status, next_run_at, id)
    WHERE status IN ('PENDING', 'RUNNING');

CREATE TABLE app.message_submissions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_no       VARCHAR(64) NOT NULL UNIQUE CHECK (btrim(submission_no) <> ''),
    source_message_id   BIGINT NOT NULL REFERENCES app.channel_messages(id) ON DELETE RESTRICT,
    status              VARCHAR(16) NOT NULL DEFAULT 'RECEIVED'
                        CHECK (status IN ('RECEIVED', 'INTERPRETED', 'FAILED', 'DRAFTED', 'CONFIRMED', 'REJECTED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_message_submissions_message
    ON app.message_submissions (source_message_id);

CREATE TABLE app.message_media (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id       BIGINT REFERENCES app.message_submissions(id) ON DELETE RESTRICT,
    channel_message_id  BIGINT REFERENCES app.channel_messages(id) ON DELETE RESTRICT,
    channel_media_id    VARCHAR(255) NOT NULL CHECK (btrim(channel_media_id) <> ''),
    media_type          VARCHAR(32) NOT NULL CHECK (media_type IN ('image', 'file', 'voice', 'video')),
    download_status     VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                        CHECK (download_status IN ('PENDING', 'DOWNLOADING', 'AVAILABLE', 'FAILED')),
    content_ref         VARCHAR(512),
    content_hash        VARCHAR(128),
    content_type        VARCHAR(128),
    size_bytes          BIGINT CHECK (size_bytes IS NULL OR size_bytes >= 0),
    decrypt_info        JSONB,
    failure_reason      TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (channel_message_id, channel_media_id),
    CHECK (num_nonnulls(submission_id, channel_message_id) > 0)
);

CREATE INDEX idx_message_media_submission ON app.message_media (submission_id);
CREATE INDEX idx_message_media_download ON app.message_media (download_status, id);

CREATE TABLE app.message_interpretations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id       BIGINT NOT NULL REFERENCES app.message_submissions(id) ON DELETE RESTRICT,
    version             INT NOT NULL CHECK (version >= 1),
    provider            VARCHAR(128) NOT NULL CHECK (btrim(provider) <> ''),
    model               VARCHAR(128) NOT NULL CHECK (btrim(model) <> ''),
    prompt_version      VARCHAR(64) NOT NULL CHECK (btrim(prompt_version) <> ''),
    intent              VARCHAR(32) NOT NULL
                        CHECK (intent IN ('CUSTOMER_ORDER', 'SUPPLIER_TRACKING', 'ORDER_CHANGE',
                                          'ORDER_CANCEL', 'NON_BUSINESS', 'NEED_REVIEW')),
    structured_output   JSONB NOT NULL DEFAULT '{}'::JSONB CHECK (jsonb_typeof(structured_output) = 'object'),
    error               TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (submission_id, version)
);

CREATE INDEX idx_message_interpretations_submission
    ON app.message_interpretations (submission_id, version DESC);

CREATE TABLE app.order_drafts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_no             VARCHAR(64) NOT NULL UNIQUE CHECK (btrim(draft_no) <> ''),
    submission_id        BIGINT NOT NULL REFERENCES app.message_submissions(id) ON DELETE RESTRICT,
    source_order_no      VARCHAR(128) NOT NULL CHECK (btrim(source_order_no) <> ''),
    customer_id          BIGINT REFERENCES app.customers(id) ON DELETE RESTRICT,
    customer_candidates  JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(customer_candidates) = 'array'),
    customer_name_raw    TEXT,
    receiver_name        TEXT,
    receiver_phone       TEXT,
    receiver_address     TEXT,
    settlement_method    VARCHAR(32),
    missing_fields       JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(missing_fields) = 'array'),
    status               VARCHAR(16) NOT NULL DEFAULT 'OPEN'
                         CHECK (status IN ('OPEN', 'CONFIRMED', 'REJECTED')),
    revision             BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
    confirmed_by         VARCHAR(128),
    confirmed_at         TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'OPEN' AND confirmed_by IS NULL AND confirmed_at IS NULL)
        OR (status IN ('CONFIRMED', 'REJECTED') AND confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)
    )
);

CREATE INDEX idx_order_drafts_submission ON app.order_drafts (submission_id);
CREATE INDEX idx_order_drafts_status ON app.order_drafts (status, created_at DESC);

CREATE TABLE app.order_draft_lines (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_draft_id       BIGINT NOT NULL REFERENCES app.order_drafts(id) ON DELETE RESTRICT,
    line_no              INT NOT NULL CHECK (line_no >= 1),
    sku_id               BIGINT REFERENCES app.skus(id) ON DELETE RESTRICT,
    sku_candidates       JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(sku_candidates) = 'array'),
    product_name_raw     TEXT,
    spec_raw             TEXT,
    unit_raw             TEXT,
    quantity             NUMERIC(18, 3) CHECK (quantity IS NULL OR quantity > 0),
    fulfilled_quantity   NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (fulfilled_quantity >= 0),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_draft_id, line_no)
);

CREATE INDEX idx_order_draft_lines_draft ON app.order_draft_lines (order_draft_id);

CREATE TABLE app.provider_tracking_drafts (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_no              VARCHAR(64) NOT NULL UNIQUE CHECK (btrim(draft_no) <> ''),
    submission_id         BIGINT NOT NULL REFERENCES app.message_submissions(id) ON DELETE RESTRICT,
    line_no               INT NOT NULL CHECK (line_no >= 1),
    raw_receiver_name     TEXT,
    masked_receiver_name  TEXT,
    tracking_no           VARCHAR(128),
    carrier_code          VARCHAR(64),
    carrier_candidates    JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(carrier_candidates) = 'array'),
    task_id               BIGINT REFERENCES app.fulfillments(id) ON DELETE RESTRICT,
    task_candidates       JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(task_candidates) = 'array'),
    shipment_judgment     VARCHAR(32) NOT NULL DEFAULT 'FULL'
                          CHECK (shipment_judgment IN ('FULL', 'PARTIAL', 'SHORTAGE', 'EXCEPTION')),
    actual_quantity       NUMERIC(18, 3) CHECK (actual_quantity IS NULL OR actual_quantity >= 0),
    validation_issues     JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (jsonb_typeof(validation_issues) = 'array'),
    status                VARCHAR(16) NOT NULL DEFAULT 'OPEN'
                          CHECK (status IN ('OPEN', 'CONFIRMED', 'REJECTED')),
    revision              BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
    confirmed_by          VARCHAR(128),
    confirmed_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'OPEN' AND confirmed_by IS NULL AND confirmed_at IS NULL)
        OR (status IN ('CONFIRMED', 'REJECTED') AND confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)
    )
);

CREATE INDEX idx_tracking_drafts_submission ON app.provider_tracking_drafts (submission_id);
CREATE INDEX idx_tracking_drafts_status ON app.provider_tracking_drafts (status, created_at DESC);
CREATE INDEX idx_tracking_drafts_task ON app.provider_tracking_drafts (task_id) WHERE task_id IS NOT NULL;

CREATE TABLE app.channel_identities (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_id             VARCHAR(128) NOT NULL CHECK (btrim(corp_id) <> ''),
    access_type         VARCHAR(64) NOT NULL CHECK (btrim(access_type) <> ''),
    channel_identity    VARCHAR(255) NOT NULL CHECK (btrim(channel_identity) <> ''),
    customer_id         BIGINT REFERENCES app.customers(id) ON DELETE RESTRICT,
    display_name        VARCHAR(255),
    remark              TEXT,
    description         TEXT,
    avatar_url          VARCHAR(512),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (corp_id, access_type, channel_identity)
);

CREATE INDEX idx_channel_identities_customer ON app.channel_identities (customer_id);

-- ---------------------------------------------------------------------------
-- review_cases 扩展：草稿主体引用与“恰好一个主体”约束
-- 老业务主体（order/order_line/fulfillment/shipment/import_batch/raw_import_row）
-- 保持原有“至少一个”语义；新草稿主体（submission/order_draft/tracking_draft）
-- 必须恰好一个且不与业务主体混用。
-- ---------------------------------------------------------------------------

ALTER TABLE app.review_cases
    ADD COLUMN message_submission_id BIGINT REFERENCES app.message_submissions(id) ON DELETE RESTRICT,
    ADD COLUMN order_draft_id BIGINT REFERENCES app.order_drafts(id) ON DELETE RESTRICT,
    ADD COLUMN provider_tracking_draft_id BIGINT REFERENCES app.provider_tracking_drafts(id) ON DELETE RESTRICT;

-- 移除 V1 的“至少一个业务主体”检查，替换为新的双分支检查
DO $$
DECLARE
    con_name TEXT;
BEGIN
    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'app.review_cases'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%num_nonnulls%';
    IF con_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE app.review_cases DROP CONSTRAINT %I', con_name);
    END IF;
END $$;

ALTER TABLE app.review_cases
    ADD CONSTRAINT review_cases_subject_check CHECK (
        (
            num_nonnulls(order_id, order_line_id, fulfillment_id, shipment_id,
                         import_batch_id, raw_import_row_id) > 0
            AND num_nonnulls(message_submission_id, order_draft_id, provider_tracking_draft_id) = 0
        )
        OR
        (
            num_nonnulls(order_id, order_line_id, fulfillment_id, shipment_id,
                         import_batch_id, raw_import_row_id) = 0
            AND num_nonnulls(message_submission_id, order_draft_id, provider_tracking_draft_id) = 1
        )
    );

-- 开放事项唯一性扩展到草稿主体
DROP INDEX app.uq_review_case_open_subject_reason;
CREATE UNIQUE INDEX uq_review_case_open_subject_reason ON app.review_cases(
    reason_code,
    (COALESCE(order_id, 0)),
    (COALESCE(order_line_id, 0)),
    (COALESCE(fulfillment_id, 0)),
    (COALESCE(shipment_id, 0)),
    (COALESCE(import_batch_id, 0)),
    (COALESCE(raw_import_row_id, 0)),
    (COALESCE(message_submission_id, 0)),
    (COALESCE(order_draft_id, 0)),
    (COALESCE(provider_tracking_draft_id, 0))
) WHERE status = 'OPEN';

CREATE INDEX idx_review_cases_submission ON app.review_cases (message_submission_id);
CREATE INDEX idx_review_cases_order_draft ON app.review_cases (order_draft_id);
CREATE INDEX idx_review_cases_tracking_draft ON app.review_cases (provider_tracking_draft_id);
