-- 受信来源模板是 AutomaticRelease 的 standing authorization；结构身份不可改写，
-- TRUSTED 一个状态同时授权自动确认与既有京东出站提交，不拆第二套开关。
CREATE TABLE app.source_template_profiles (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_no              VARCHAR(64) NOT NULL UNIQUE CHECK (btrim(profile_no) <> ''),
    source_channel          VARCHAR(32) NOT NULL
                            CHECK (source_channel IN (
                                'CAISHIXIAN', 'JUFUBAO', 'FEIXIANG', 'ZHONGHUI',
                                'DAZHE', 'WANGQI', 'WANQI', 'WECOM')),
    template_family         VARCHAR(128) NOT NULL CHECK (btrim(template_family) <> ''),
    template_version        VARCHAR(64) NOT NULL CHECK (btrim(template_version) <> ''),
    template_fingerprint    VARCHAR(128) NOT NULL CHECK (btrim(template_fingerprint) <> ''),
    status                  VARCHAR(16) NOT NULL CHECK (status IN ('TRUSTED', 'REVOKED')),
    trusted_from_batch_id   BIGINT NOT NULL REFERENCES app.import_batches(id) ON DELETE RESTRICT,
    trusted_by              VARCHAR(128) NOT NULL CHECK (btrim(trusted_by) <> ''),
    trusted_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by              VARCHAR(128),
    revoked_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_channel, template_family, template_version, template_fingerprint),
    CHECK (
        (status='TRUSTED' AND revoked_by IS NULL AND revoked_at IS NULL)
        OR (status='REVOKED' AND revoked_by IS NOT NULL
            AND btrim(revoked_by) <> '' AND revoked_at IS NOT NULL)
    )
);

CREATE INDEX idx_source_template_profiles_trusted
    ON app.source_template_profiles(source_channel, template_fingerprint)
    WHERE status='TRUSTED';

CREATE FUNCTION app.protect_source_template_profile_identity() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.profile_no IS DISTINCT FROM OLD.profile_no
       OR NEW.source_channel IS DISTINCT FROM OLD.source_channel
       OR NEW.template_family IS DISTINCT FROM OLD.template_family
       OR NEW.template_version IS DISTINCT FROM OLD.template_version
       OR NEW.template_fingerprint IS DISTINCT FROM OLD.template_fingerprint
       OR NEW.trusted_from_batch_id IS DISTINCT FROM OLD.trusted_from_batch_id
       OR NEW.trusted_by IS DISTINCT FROM OLD.trusted_by
       OR NEW.trusted_at IS DISTINCT FROM OLD.trusted_at
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'source template profile identity is immutable';
    END IF;
    IF OLD.status='REVOKED' AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'revoked source template profile cannot be trusted again';
    END IF;
    IF OLD.status='REVOKED'
       AND (NEW.revoked_by IS DISTINCT FROM OLD.revoked_by
            OR NEW.revoked_at IS DISTINCT FROM OLD.revoked_at) THEN
        RAISE EXCEPTION 'revoked source template profile evidence is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_source_template_profile_identity_immutable
BEFORE UPDATE ON app.source_template_profiles
FOR EACH ROW EXECUTE FUNCTION app.protect_source_template_profile_identity();
